### ISSUE TITLE
Error when using docker-compose up: "ModuleNotFoundError: No module named 'superset.app'"

### ISSUE THREAD

**Issue by devlace** [apache/incubator-superset#10196]
When attempting to run "docker-compose up", I'm getting an error in superset_1 "ModuleNotFoundError: No module named 'superset.app'". When navigating to localhost:8088. I get the error "flask.cli.NoAppException: Could not import "superset.app"'

### Expected results
After running docker-compose up, I expect a functioning app at localhost:8088

### Actual results
Error when navigating to localhost:8088

#### Screenshots

![image](https://user-images.githubusercontent.com/5771063/86075721-faf97000-bacb-11ea-93f4-c24e0f98348e.png)

![image](https://user-images.githubusercontent.com/5771063/86075785-254b2d80-bacc-11ea-9059-a8e2387b29ea.png)

#### How to reproduce the bug

1. Clone repo, and checkout tag 0.36.0 (latest release as of 2020/06/30).
2. cd in to incubator-superset
3. Run docker-compose up

### Environment

- superset version: 0.36.0
- docker engine version: 19.03.8
- docker compose version: 1.26.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Please attempt rebuilding from scratch as described here: https://github.com/apache/incubator-superset/issues/10149#issuecomment-671067844

Please re-open if that does not resolve your issue.

**Comment by petsasj** [comment]
I have the exact same issue.

Tried the nuke method in the linked comment, however nothing changed.

I also tried to check out different branches - as in previous versions to no avail.


Here's the system info:
OS: centos 7.7
Superset version: 0.37.2 (latest) [also tested 0.36]
Docker version: 1.13.1
Docker-compose version: 1.27.4

I figured it was a better option to comment on this issue rather than opening a new one.

I can provide further Log files if needed
