### ISSUE TITLE
React CRUD filters show duplicated values in the database filter

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#10441]
In the react views a new filter shows duplicated values while filtering on the database

### Expected results

See distinct values in the filter

### Actual results

what actually happens.
![image](https://user-images.githubusercontent.com/5727938/88587726-3c1d6b00-d00b-11ea-8452-fa174c7450eb.png)

Also schema dropdown is not working:
![image](https://user-images.githubusercontent.com/5727938/88587846-7555db00-d00b-11ea-94e8-f28edc00c2b8.png)

cc @nytai

**Comment by bkyryliuk** [comment]
Synced with @nytai on slack:
* https://github.com/dropbox/incubator-superset-internal/commit/a7aec30301a363df96f9d723ba9a36d7894f5012 causes weird behavior for me for the pagination, will revert that internally

There are 2 small outstanding issues:
1. http://localhost:8088/api/v1/database/schemas/?q=(filter:superset)  - this endpoint talked to external databases & may time out / do not have all schemas, probably it would be great to leverage `Table` table as a source of truth

2. http://localhost:8088/api/v1/database/?q=(columns:!(database_name,id),filter:presto,keys:!(none),page:1) returns extra results & doesn't apply the filter

**Comment by nytai** [comment]
@bkyryliuk Thanks for syncing with me today. I believe I've addressed the 2 points in the linked PR. 

1. We are now fetching the schema list from `/api/v1/dataset` which should return the schemas current being used in datasets. see: https://github.com/apache/incubator-superset/pull/10442/files#diff-ada33b933cd3086338ea8c3250ad87b3R86
2. The extra results are due to removing pagination constraints via https://github.com/dropbox/incubator-superset-internal/commit/a7aec30301a363df96f9d723ba9a36d7894f5012. The endpoint being called was also moved over to `/ap1/v1/dataset/related/database` which should properly handle filtering. 

Let me know if you'd like help confirming the PR fixes these issues.
