### ISSUE TITLE
Cannot login using default username and password

### ISSUE THREAD

**Issue by PhucNgo1711** [apache/incubator-superset#10547]
This is my first time using Superset and I followed the instructions here 
https://superset.apache.org/installation.html#start-with-docker

### Expected results
I was able to clone and run `docker-compose up` successfully. 
I opened `http://localhost:8088` on my browser and entered `admin` for both username and password. 

### Actual results

I got an `Invalid login. Please try again.` message

#### Screenshots

![Screen Shot 2020-08-07 at 1 31 18 AM](https://user-images.githubusercontent.com/14838084/89612407-be006600-d84d-11ea-98d4-408581d12662.png)

#### How to reproduce the bug

I followed https://superset.apache.org/installation.html#start-with-docker

### Environment

- superset version: `NA`
- python version: `3.7.3`
- node.js version: `11.0..0`
- npm version: `6.14.4`

**Comment by llxnqueen** [comment]
same problem, hope for an answer soon！

**Comment by skorski** [comment]
Ditto.  I'm wondering if something happened to the docker file.  I tried running the superset-init script but got:

```
‘bash\r’: No such file or directory
```

Would love to help put in  PR if someone could give me more direction.  I'm new to this repo.

**Comment by rgarci** [comment]
I guess you're running on windows, this is a problem caused by git cause it has a default configuration that changes Unix-style line breaks to windows ones, in order to surpass this you need to:

- delete your current repo
- apply `git config --global core.autocrlf false` so it doesn't change the line breaks
- clone the repo again
Now you won't be seing this error

checkout : https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory

**Comment by PhucNgo1711** [comment]
I have this issue on `macOS`

**Comment by PhucNgo1711** [comment]
Ah this is a duplicate of #10149.
