### ISSUE TITLE
SQL Injection - High Severity - A SQL injection attack consists of insertion or “injection” of a SQL query via the input data from the client to the application. A successful SQL injection exploit can read sensitive data from the database

### ISSUE THREAD

**Issue by kpchennai** [apache/incubator-superset#10791]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: 0.35.2
- python version: python 3.6.5
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
@kpchennai please fill out the issue template

**Comment by willbarrett** [comment]
@kpchennai if you have indeed discovered a vulnerability in Superset please email information on the vulnerability to private@superset.apache.org rather than disclosing it publicly. This will notify the project PMC members of the vulnerability and allow us to cut a new release with a security fix before publicly disclosing the vulnerability as a CVE.

**Comment by kpchennai** [comment]
@willbarrett Thanks for the info, will do the same
