### ISSUE TITLE
seek help menu icon cannot be displayed

### ISSUE THREAD

**Issue by xuningyang** [apache/incubator-superset#11324]
seek help menu icon cannot be displayed

**Comment by junlincc** [comment]
@xuningyang Please fill out the bug report or cosmetic issue templates to report issues. closing it for now. 

A clear and concise description of what the bug is.

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots

If applicable, add screenshots to help explain your problem.

#### How to reproduce the bug

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Add any other context about the problem here.
