### ISSUE TITLE
seek help menu icon cannot be displayed

### ISSUE THREAD

**Issue by xuningyang** [apache/incubator-superset#11339]
## Expected results
<img width="823" alt="企业微信截图_f8e0a494-c899-4b3d-addc-d41a2f6433c6" src="https://user-images.githubusercontent.com/30031192/96552412-4daea000-12e6-11eb-9bc5-d52e34a015f9.png">

## Actual results
<img width="1020" alt="企业微信截图_2b9253c0-53c6-4e5e-9af0-49c3da81e84b" src="https://user-images.githubusercontent.com/30031192/96552678-b138cd80-12e6-11eb-8aa9-ab5e94b5d840.png">

## Environment
python: python 3.6
npm: 6.14.6
Superset 0.999.0dev
node:v12.18.3

## Description
superset back-end starts normally, and the front-end compilation has no errors.
After entering superset, the public menu bar cannot display the icon

**Comment by zhaoyongjie** [comment]
hi @xuningyang . I checked the icon conf in FAB, like this
https://github.com/apache/incubator-superset/blob/cae54ac00e154ddfb0699e0dde7233b5942c5e70/superset/app.py#L217-L225
 
so I guess have some font style overwrite the existing FAB icon.

**Comment by junlincc** [comment]
Hi @xuningyang and @zhaoyongjie We removed these nav bar icons while we reorganized the navigation by design, to get closer to the proposed design in [SIP-34](https://github.com/apache/incubator-superset/issues/8976) for keeping the cleanness and consistency. if you would like to make any contributions on improving the UI, SIP-34 can be a good guideline.
