### ISSUE TITLE
[table chart] raw records SELECT ALL option is broken

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11368]
Table chart's select all option is broken.

#### Screenshots

![GsJ1Jnqey4](https://user-images.githubusercontent.com/27990562/96763089-6377a000-138e-11eb-85b7-0a23c1f5142b.gif)

### Environment
lastest master branch

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
any idea which PR caused it? i dont recall anyone touched this area lately.

**Comment by zuzana-vej** [comment]
@junlincc  it looks like this issue is still there. I think it could have been caused by earlier redesigns on the Explore page - similar as what caused https://github.com/apache/incubator-superset/issues/11379 or https://github.com/apache/incubator-superset/issues/11404 (just a guess, it's also ~2-3 weeks old issue, so discovered around the same time).

**Comment by junlincc** [comment]
on it @graceguo-supercat @zuzana-vej

**Comment by kgabryje** [comment]
@junlincc I don't think I did any changes to those Select buttons, but I'm on it!

**Comment by junlincc** [comment]
> @junlincc I don't think I did any changes to those Select buttons, but I'm on it!

i dont think so either! then the next person who touched this area was Jesse maybe 😆 but thank you @kgabryje for the fix.🙏 
tested, all good! 
![ezgif-6-96a705d00f6f](https://user-images.githubusercontent.com/67837651/99329979-42428c00-2834-11eb-8a00-a2e8a8ebb81e.gif)

**Comment by kgabryje** [comment]
I looked through the changes and after all it was a regression caused by my PR from September - https://github.com/apache/incubator-superset/pull/10889. I refactored a `for… of… loop` to `forEach` in order to fix ESLint errors - however, there was a `return` statement inside. In the old version, it returned from the whole function and after refactor, it returned only from `forEach`, causing the outer function to keep running and finally breaking the result.
