### ISSUE TITLE
SQL Lab problems displaying buttons in toolbar and icons in table context menu

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11715]
On latest `master`, notice 2 issues related to right-floating controls
- on toolbar
- in the table on-hover context menu 

<img width="1561" alt="Screen Shot 2020-11-16 at 9 39 01 AM" src="https://user-images.githubusercontent.com/487433/99287909-b9096600-27ef-11eb-812b-60775a03f9ff.png">

**Comment by junlincc** [comment]
<img width="917" alt="Screen Shot 2020-11-16 at 9 48 28 AM" src="https://user-images.githubusercontent.com/67837651/99288954-2d90d480-27f1-11eb-8730-701279539840.png">
might related?

**Comment by junlincc** [comment]
@yousoph the bug is fixed, but the left panel still seems too crowded. I think the sql editor doesn't need that much of the space, but your call! 
<img width="320" alt="Screen Shot 2020-11-16 at 6 15 44 PM" src="https://user-images.githubusercontent.com/67837651/99337774-c64a4300-2837-11eb-8939-b99849f6b347.png">
