### ISSUE TITLE
How to use redis cluster in caravel(superset)?

### ISSUE THREAD

**Issue by hibobby** [apache/incubator-superset#1716]
Make sure these boxes are checked before submitting your issue - thank you!

- [√ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ √] I have reproduced the issue with at least the latest released version of superset
- [ √] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 
0.12.0

### Expected results 
 Can use redis cluster in caravel(superset).

### Actual results
I find none of  flash-cache,werkzeug,redis-py support using redis cluster.
So caraverl(supertset) can not use redis cluster.

**Comment by xrmx** [comment]
Caching is superset is handled by flask-cache, if it does not support redis cluster then we cannot support redis cluster. Since redis-py-cluster exposes the very same redis-py api it looks like a configuration issue to me.

@ioshger0125 you may want to help each other and possibly update flask-cache documentation :)

**Comment by hibobby** [comment]
Do you mean that we need to replace redis-py with redis-py-cluster, and then modify the code for configuration in flash-cache?

**Comment by xrmx** [comment]
@hibobby yes, that's what reading issue #1717 and a 2 minute google search suggested :)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 508 days. Feel free to comment and request for this issue to be reopened.
