### ISSUE TITLE
The horizontal scroll bar isn't displayed on IE11

### ISSUE THREAD

**Issue by corselia** [apache/incubator-superset#1895]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.1

### Expected results
- The horizontal scroll bar is displayed

### Actual results
- The horizontal scroll bar is not displayed
    - only on IE11
    - I confirmed correct displayed on Chrome and Firefox

### Steps to reproduce
- select `Time Series - Bar Chart` as `Visualization Type`
- set `Time`, `Metrics` and part of `Chart Options`
- When `Reduce X ticks` unchecked,  the horizontal scroll bar isn't displayed on IE11
    - refer to attached image

![horizonal-scroll-bar-is-not-displayed-on-ie11](https://cloud.githubusercontent.com/assets/14275619/21631298/ea259014-d27c-11e6-8542-1694ee9988ae.png)

**Comment by ama-ableton** [comment]
I have the same issue on Superset 0.15.4 with Firefox and Chrome on Mac. This seems to happen because of some minimum width of the bars, such that sometimes min-width * number of bars > width of slice.  

When refreshing a slice, it shows the whole range for a moment with thinner bars before the final redraw, then finally draws the bars wider, making the chart go outside of the bounds of the slice.  

I've added this custom css to my dashboards as a workaround:
```
div.widget .slice_container {
  overflow: auto;  //was overflow:hidden
}
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 422 days. Feel free to comment and request for this issue to be reopened.
