### ISSUE TITLE
[feature] Visualising Datasource, Table, Slice and Dashboard Use.

### ISSUE THREAD

**Issue by alanmcruickshank** [apache/incubator-superset#1928]
New Feature Suggestion for feature. (I'm happy to implement this but wanted people's thoughts first)

In the "Manage" section, a way of visualising the usage of datasources, tables, slices and dashboards. Goals being to identify high and low use tables and slices to prune old or stale ones.

My suggestion would probably be a D3 network diagram (http://bl.ocks.org/mbostock/4062045) where the size of each node is dictated by how much the item gets used.

One extension would also be to show which metrics and columns are getting used the most too.

**Comment by dylburger** [comment]
I love this idea and just wanted to add some thoughts.

Is the activity log of usage (e.g. the database, table, slice, user, datetime of query, etc.) recorded anywhere today?

If that log exists (of if we start recording it), you could open that up for exploration so that admins could ask abstract questions of the data (Who's the top user? During what time of the day do we see the most query activity against table X? etc.).

I like the notion of a specific viz, and I think it'd be cool to display the most important usage stats in something fixed like the network diagram, but it seems easier to expose the event-level stats in an intuitive way and let admins create their own usage dashboard specific to their environment.

**Comment by mistercrunch** [comment]
We have a nice `Superset Usage` dashboard at Airbnb where we track usage over time. Weekly active users, daily active user, recent hourly usage, popular viz types, top dashboards over the past 7 days, top slices, number of content creators, ... We should take the time to ship this along with the examples so that people can track adoption ramping up in their environments.

**Comment by alanmcruickshank** [comment]
@mistercrunch that sounds good, I think that should ship as default when you run `superset init`. I think this would be additive to that though. This is more about seeing the connections. For example it's quite hard to find out which dashboards use a particular metric at the moment, so I don't always know if it's safe to remove. That's eventually the use case I want to cover. Thoughts?

@dylburger we do store the logs, but the parts on metrics and columns are currently stored as json rather as individual values. You can see the logs in the `access logs` menu item.

**Comment by dylburger** [comment]
@alanmcruickshank very cool. My only feedback here would still be: is there a way to expose both the log data (potentially flattening some of the properties stored in the JSON, projecting them as easily-queryable values) and the slice / dashboard metadata in a more accessible way for querying, so that you enable admins to ask _any_ general questions of that data.

Again, I like the idea of your network viz for your use case, but I'm imaging admins asking _many_ arbitrary questions about their instance, and your viz might not target all of them.

Maybe this is a separate story from yours - just wanted to put the thoughts on paper in case they help.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 466 days. Feel free to comment and request for this issue to be reopened.

**Comment by ShahNewazKhan** [comment]
Just wondering if there was an implementation of this feature? Thanks in advance!
