### ISSUE TITLE
sqllab in the non-stop sending requests

### ISSUE THREAD

**Issue by wuwutai** [apache/incubator-superset#1945]
hi,when i was using sqllab,i have a question,as shown below
![2323](https://cloud.githubusercontent.com/assets/3643703/21833037/5fb8a934-d7ea-11e6-977f-76fe76267e1f.png)
,there is always a request to send non-stop,so i read the return result is empty,is seems useless,do you know?
   And, only when using sqllab cpu value is high and did not come down, I doubt with this place

**Comment by ascott** [comment]
it looks like this xhr request is happening in the `QueryAutoRefresh` component, in order to show an OFFLINE label if the network is down.

https://github.com/ascott/superset/blob/master/superset/assets/javascripts/SqlLab/components/QueryAutoRefresh.jsx#L29

https://github.com/ascott/superset/blob/master/superset/assets/javascripts/SqlLab/components/Sql
EditorLeftBar.jsx#L98

@mistercrunch do you have any insight here? do you think the OFFLINE label is really important to have?

**Comment by wuwutai** [comment]
@mistercrunch ?

**Comment by zhaodedong** [comment]
I encountered this problem too，was it solved in 0.15.1?

**Comment by wuwutai** [comment]
@zhaodedong no,I was using the 0.15.1 version of the problem

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 462 days. Feel free to comment and request for this issue to be reopened.
