### ISSUE TITLE
Add Apache Drill as a connector

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#1993]
C. Givre wrote in a different channel:
--------------
I'm working on a SQLAlchemy dialect for Apache Drill so that I can use Superset with Drill. 
My intention is to open source it once it works reasonably well and consistently, but I keep running into small issues and I wanted to ask if you would be willing to assist me from time to time by answering some small questions I have. 

I'll tell you that the biggest challenge I've encountered is that Drill doesn't record the data types which are returned in a query. So for every query, I've had to create a secondary query using the 'typeof()' method in order to obtain the data types. This works reasonably well, but I'm getting a lot of malformed queries when I try to generate charts from Superset.

My preference is not to put these on the Superset issue tracker as the issues probably aren't issues with Superset but rather the dialect. Anyway, thanks in advance for whatever help you can give me.

-----------

Notes from @mistercrunch
* the datasource interface is not very well defined at the moment and I'd like to do some work in that direction. My vision is to have a clear base class for Datasource, Column and Metric that would need to be derived for each "connector". In the meantime you kind of have to infer the interface which isn't ideal at all, especially as we add more connectors. The first step is to identify everything that is common to the Druid and SQLAlchemy classes and refactor that in a base class. Also probably breaking down into more python modules, maybe under a new `connectors` folder, with `base.py`, `druid.py` and `sqlalchemy.py`.
* what about inferring types when saving the Drill datasource somehow, maybe by running a dummy query of some sort with a low limit
* it's ok to add issues and PRs about Drill in this repository. Depending on your commitment and level of support we may put it alongside other connectors, or in a `contrib` folder. Though I think it would be great if you wanted to bring that in and you essentially become the maintainer of that part of the code. Over time and as trust build we can provide you with more rights on the repository.
* eventually we should write a "Connectors" page in the docs telling users what they need to know about connectors
* eventually we should add a "Adding a connector" section to the `CONTRIBUTING.md`

**Comment by cgivre** [comment]
All,
I've been working on getting this to work.  @JohnOmernik started a sqlalchemy dialect which used PyODBC to connect to Drill.  I had a lot of issues getting Drill to work via ODBC so I decided to use PyDrill which makes use of Drill's RESTFul interface and hence requires no configuration.  

However, PyDrill is not DBAPI compliant. :-( 
So... I had to write a DBAPI module for PyDrill to make that work.  

The biggest challenge which I'm encountering is the data type issue.  What I've done is as follows:
- If the field is a known function, problem solved.
- Otherwise, create a secondary query which uses the `typeof()` function to determine the data type.  
So... for example:

```
SELECT field1, field2
FROM dfs.test.`data.csv`
```
executes a secondary query:
```
SELECT field1, typeof( field1 ) AS field1_type, field2, typeof( field2 ) AS field2_type
FROM dfs.test.`data.csv`
```
While this works, there are a lot of edge cases in parsing the SQL.  You have to extract the fields which can be column names, subqueries, functions etc. and that can be complex.  Additionally, aggregate queries will break this model, so I've been trying to figure out a workaround for that.   I just found a module called `sqlparse` which I'm in the process of using to rewrite some of this code.  I believe that it will be much more reliable once I'm done with that.

All of this is actually done in the DBAPI module, not the SQLAlchemy dialect.

In any event, here is the code for the sqlalchemy dialect.   I will post the PyDrill DBAPI module to this thread shortly. 

https://github.com/cgivre/sqlalchemy-drill/tree/pydrill

Using this code, I've gotten Superset to:

- Connect to Drill
- Retrieve available workspaces
- Retrieve tables (files)
- In SQL Lab execute arbitrary queries
- Do some (but not all) visualizations in Superset

If anyone is interested in assisting, I'd really appreciate the help.

**Comment by cgivre** [comment]
BTW... @mistercrunch I'm actually of the opinion that it probably would be better to have a dedicated connector for Drill as opposed to using SQLAlchemy.  I've really been struggling with SQLAlchemy and if there was some documentation about a connector in Superset, I'd definitely have a go at that.

**Comment by cgivre** [comment]
@mistercrunch @JohnOmernik 
Here is the DBAPI for PyDrill.  I'm need to package this as its own module, but this does work.  Simply install pydrill then copy the contents of this archive into `<python-path>/site-packages/pydrill/` directory.  My intent is to submit a PR for PyDrill to get the DBAPI incorporated into that module, but I have to write up unit tests and test it on all the various python versions so that might take a while. 

Once you have this, then install this: https://github.com/cgivre/sqlalchemy-drill/tree/pydrill using `python setup.py install -- force` and you'll be able to connect Superset and Drill. 

[dbapi.zip](https://github.com/airbnb/superset/files/742547/dbapi.zip)

With all that said, the dialect and the DBAPI do work and I've been able to successfully create some charts and graphs with them.  I haven't been able to get any of the timeseries visualizations to work, and I'm not quite sure why yet.  I've also been able to execute arbitrary SQL statements via SQL Lab but I do run into issues when I try to visualize these statements. 

The issue is that when SQLAlchemy generates the new table it does so as follows:
SELECT field1, field2
FROM 
(SELECT field1, field2 
FROM table 1
) AS table1___

When using Joins and subqueries, Drill requires all fields to have table names and thus it throws an error.  Also SQLAlchemy seems to generate queries that use column aliases in GROUP BY clauses which also causes problems with Drill. 

I'll go through all the visualizations and write up what works and what doesn't so that others can take a look as well.

**Comment by vikramsinghchandel** [comment]
Hi Guys any update on supporting Drill in superset?

**Comment by mistercrunch** [comment]
Looks like with the DBAPI driver and SQLAlchemy dialect most of the pieces of the puzzles are in place. Superset does need an extra thing though: an entry in db_engine_spec:
https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py#L1317
