### ISSUE TITLE
Unable to use wildcard in SQL Lab

### ISSUE THREAD

**Issue by xxdesmus** [apache/incubator-superset#2061]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
`"version": "0.15.4"`

### Expected results
`WHERE query LIKE ('%ocsp%')` matches `foo.ocsp` and also matches `ocsp.bar`

### Actual results
`(_mysql_exceptions.ProgrammingError) %o format: a number is required, not dict`

### Steps to reproduce
In SQL Lab run a search such as:
`SELECT DISTINCT LOWER(QUERY), COUNT FROM pdns WHERE query LIKE ('%ocsp%') ORDER BY count DESC limit 15;`

of note the exact same query runs without issue directly against MySQL

**Comment by ascott** [comment]
i thought we had fixed this issue so you could use a single `%` but i believe a work around is to use `%%` in your query.

does this work for you?
```sql
SELECT DISTINCT LOWER(QUERY), COUNT FROM pdns 
WHERE query LIKE ('%%ocsp%%') 
ORDER BY count 
DESC limit 15;
```

**Comment by xxdesmus** [comment]
`%%` does indeed works perfectly. Thank you!

**Comment by amalakar** [comment]
Could we re-open this issue, looks like the need of escaping is not clearly stated in the error message to the user. Also would be nice if we don't have to escape the query, because now using this query in other tool is not possible. We will have to unescape again:

<img width="1120" alt="screen shot 2019-01-30 at 3 29 31 pm" src="https://user-images.githubusercontent.com/65202/52020288-9fc1e900-24a5-11e9-87d6-5a2f3468ab40.png">

**Comment by mistercrunch** [comment]
@amalakar this is a bit tricky because different `dbapi` implementations behave differently around parameterization. We probably need a new method in `db_engine_spec` to manage driver-specific logic around this.
