### ISSUE TITLE
Refresh Datasources does not work with druid realtime segments

### ISSUE THREAD

**Issue by nishantmonu51** [apache/incubator-superset#2273]
For refresh datasources to work, superset needs physical segments actually handed over to druid historical nodes. We can improve the schema discovery to discover schema from druid realtime intermediate segments also. 

planning to work on it and will send a PR for this soon.

**Comment by mistercrunch** [comment]
I couldn't find an endpoint on our current version 0.8.? that exposes that metadata...

**Comment by mistercrunch** [comment]
Also note that at Airbnb we have a framework that loads data in Druid from config files, and that we leverage the metadata defined there to create the Datasources in Superset, meaning that at Airbnb we don't actually use the Superset code to sync datasource metadata anymore.

Say if you want to load some Kafka topic into Druid you fill in a bit of information in a config file (topic, xpath statements to deserialize payload, sample rate, filtering, dims, metrics, ...). Since we have that we use it to create the datasources, which solves the realtime use case. But of course this doesn't work for others...

**Comment by deyani27** [comment]
I have a druid cluster and have the segment-cache in historical node, yet I am unable to load the data in superset. I could see the datasources name , but refresh cluster is not pulling the data from segment-cache.
