### ISSUE TITLE
[filter box] sort values in the filter

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2367]
allow user to sort the values in the filter

**Comment by bkyryliuk** [comment]
there is a workaround via specifying the metric to be MAX or MIN

**Comment by agriffis** [comment]
It would be nice to divorce the sort from the metric, or make it selectable. Some filters (e.g. customer name) really want to be in alphabetical order. Other filters want to be in reverse alpha order, such year/quarter strings with the most recent at the top.

**Comment by caseye** [comment]
Agree with the workaround, but to clarify agriffis, due to the way the query is written by the system it creates a lot of wackiness.  For example,

--------------------
SELECT ad,
       "DC_Sort"
FROM
  (SELECT ad AS ad,
          min(ad) AS "DC_Sort"
   FROM "GGEBHART"."VW_HARDWARE_PIPELINE_UNP_ANAL"
   WHERE event_date >= TO_TIMESTAMP('2017-07-06T17:44:05', 'YYYY-MM-DD"T"HH24:MI:SS.ff6')
     AND event_date <= TO_TIMESTAMP('2017-07-13T17:44:05', 'YYYY-MM-DD"T"HH24:MI:SS.ff6')
   GROUP BY ad
   ORDER BY min(ad) DESC)
WHERE ROWNUM <= 50000
------------
-Why does the order by default to DESC with no seeming ability to change?
-Why is it limiting Rownum to under 50,000?  I mean for performance, yes... but what if I need it to look in more rows?
--Why is there an inherent time series when this has nothing to do with time?

I would actually argue that the real need is an ability to manually alter the system-generated SQL statement to make it do what you need.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 283 days. Feel free to comment and request for this issue to be reopened.

**Comment by csc5k** [comment]
+1 I think it would make sense to have options within the filter slice to default sort order to alphabetic

**Comment by mosche** [comment]
Would be great to reopen this @mistercrunch 
Also, related: https://github.com/apache/incubator-superset/issues/3272

**Comment by mistercrunch** [comment]
Finally got around to this here https://github.com/apache/incubator-superset/pull/6523
