### ISSUE TITLE
Couldn't parse date string when using date filter

### ISSUE THREAD

**Issue by cloga** [apache/incubator-superset#2649]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Actual results

![image](https://cloud.githubusercontent.com/assets/1320343/25211742/55458fc2-25b9-11e7-8c1e-bd7633370836.png)

**Comment by xrmx** [comment]
Which version of superset?

**Comment by cloga** [comment]
Superset 0.17.4
Python 2.7.13

**Comment by Csnigs** [comment]
I had the same issue on 0.17.5 with Python 2.7.
I changed the `Origin` field in the Time section of the Filter Box slice to nothing (it was set to `default` before) and that seemed to have fixed it for now
here's my filter setup now
![selection_043](https://cloud.githubusercontent.com/assets/2435414/25703213/e9d53770-30d4-11e7-9358-6678434f49d0.png)

The error message appears on all slice of the dashboard only if/when I change the `from` value in the Dashboard and `Apply` the filter (initial load of the dashboard is fine).

The stacktrace:
`2017-05-04 12:13:37,423:ERROR:root:Couldn't parse date string [[u'1', u' ', u'h', u'o', u'u', u'r', u' ', u'a', u'g', u'o']]
May 04 12:13:37 druid superset[3599]: Traceback (most recent call last):
May 04 12:13:37 druid superset[3599]:   File "/home/streamroot/supersetenv/local/lib/python2.7/site-packages/superset/viz.py", line 233, in get_payload
May 04 12:13:37 druid superset[3599]:     df = self.get_df()
May 04 12:13:37 druid superset[3599]:   File "/home/streamroot/supersetenv/local/lib/python2.7/site-packages/superset/viz.py", line 65, in get_df
May 04 12:13:37 druid superset[3599]:     query_obj = self.query_obj()
May 04 12:13:37 druid superset[3599]:   File "/home/streamroot/supersetenv/local/lib/python2.7/site-packages/superset/viz.py", line 364, in query_obj
May 04 12:13:37 druid superset[3599]:     d = super(PivotTableViz, self).query_obj()
May 04 12:13:37 druid superset[3599]:   File "/home/streamroot/supersetenv/local/lib/python2.7/site-packages/superset/viz.py", line 136, in query_obj
May 04 12:13:37 druid superset[3599]:     from_dttm = utils.parse_human_datetime(since)
May 04 12:13:37 druid superset[3599]:   File "/home/streamroot/supersetenv/local/lib/python2.7/site-packages/superset/utils.py", line 190, in parse_human_datetime
May 04 12:13:37 druid superset[3599]:     raise ValueError("Couldn't parse date string [{}]".format(s))
`

**Comment by JieChenZy** [comment]
One more comment, which may be helpful for figuring out the problem: 
The standard alone time filter gives me 'Couldn't parse date string...' error, same error as @cloga had. But if the filter has time and other dimensions, then applying filter with combination of time and any other dimension shows correct result, instead of 'Couldn't parse date string...' error. 

Python 2.7
Superset 0.17.4

**Comment by robert-digit** [comment]
Note - same issue here on 0.18.3.
