### ISSUE TITLE
Cannot create sankey diagrams with more than two source/target dimensions

### ISSUE THREAD

**Issue by brettdh** [apache/incubator-superset#3059]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
I am able to produce Sankey diagrams with a sequence of multiple sources/targets, as in the documentation:
![](https://superset.incubator.apache.org/_images/sankey.png)

### Actual results
When I try to add additional dimensions, I get this error message:
```
Pick exactly 2 columns as [Source / Target]
```

### Steps to reproduce
Data source is Druid.

1. Navigate to the data source and click on it to open the Explore view
1. Change Visualization Type to Sankey
1. Notice that the UI *also* indicates a Sankey with more then two sources/targets 🤔 
1. Select more than two dimensions in the "Source/Target" dropdown
1. Click "Query"

**Comment by wzhang0** [comment]
I had the same problem before, and get fixed by correcting the data set structure. You should use UNION to connect tables.

For example:
select source, connect_1, sum(revenue) as income, 'test' from your_table group by 1,2 
union
select connect_1, target, sum(revenue) as income, 'test' from your_table group by 1

And then try to visualize by sankey diagrams.

**Comment by wzhang0** [comment]
I had the same problem before, and get fixed by restructure my data set by UNION. 
Try the following:

Select source, layer1, revenue, 'test' from your_table 
UNION
Select layer1, target, revenue 'test' from your_table

And then try to visualize it by sankey diagram.
metric = sum(revenue)

**Comment by mistercrunch** [comment]
The data needs to be prepared in a source->target way. Parent-child if you prefer. To do a chain a-b-c-d you provide the data as:
```
a-b
b-c
c-d
```

**Comment by brettdh** [comment]
@wzhang0 that makes sense for SQL rows, but....

@mistercrunch I'm having trouble understanding how that'd be possible in Druid. In your example, a and b are different columns, but the UNION that @wzhang0 used to produce that data doesn't have a clear analogue in Druid, to my knowledge anyway.

**Comment by mistercrunch** [comment]
How else do you want to represent a graph in a table? source->target is the proper way to model it.

Maybe you're trying to do something simpler like representing a linear funnel?

Think about it, in a Sankey data points can come in or drop out at any node, and skip step(s). A column representation of that would come short in many ways.

**Comment by pajachiet** [comment]
I encounter the same need, which is to do a Sankey Diagram from multiple source/target pairs in the same table. This is natural when "columns" that appear in the sankey diagram correspond to columns in a table. 

In SQL, it can be done with UNION, but it is cumberome. Even more if you want to base other visualizations on the same datasource, as you have to dupplicate rows informations.

For example if we want to represent how towns population regroup into states and countries, with a table ('country', 'state', 'town', 'population'), we would do
```
SELECT    
    town as source, state as target, 
    country, state, town, population
FROM your_table
UNION
SELECT 
   state as source, country as target, 
   country, state, town, population
FROM your_table
```

Would it be possible to do this union directly in the query generated for the visualization ?

**Comment by pajachiet** [comment]
And to give a better example, here is a dashboard based on superset backend. 
[superset_dashboard_role-datasource-dashboard_relations.pickle.zip](https://github.com/apache/incubator-superset/files/1336261/superset_dashboard_role-datasource-dashboard_relations.pickle.zip)

<img width="1406" alt="superset role-table-dashboard" src="https://user-images.githubusercontent.com/4091226/30903272-7f829842-a36e-11e7-94e2-339bdbd07542.png">

It shows with a Sankey diagram the relationships between role and datasource (access rights), then between datasource and dashboards (through slices). 

This is great for us to see who has access to which datasource, and in the same glance to which dashboards. It also helps us to make sure dashboards are based on only one datasource (so that filters works).
But the underlying [sql request](https://gist.github.com/pajachiet/ccdddd1ec2d06ebb9060ee4d8d17a9c2) has to do the UNION.

**Comment by mistercrunch** [comment]
@pajachiet neat!

**Comment by mlmaverick** [comment]
Hi, even after restructuring, I don't get the multi-level Sankey diagram. I'm using 1.5.0 version. Something I need to be doing differently?

**Comment by mlmaverick** [comment]
Hi all, can someone please help with #20887. Thanks. @mistercrunch @pajachiet @wzhang0

**Comment by galrapo** [comment]
Looking forward to hear more if this issue is resolved.
We will highly appreciate your support on this case

**Comment by ariel-sofi** [comment]
Opened https://github.com/apache/superset/pull/42477, which adds an optional ordered **Intermediate levels** column control to the Sankey chart. With it set, the query groups by `[source, ...intermediate levels, target]` and the transform emits links for each adjacent pair, so `Country → Product → Channel → Outcome` renders as four levels of nodes from a single dataset — no `UNION ALL` virtual dataset needed.

This issue was closed as stale rather than fixed, so flagging it here for anyone still subscribed. Backward compatible: `intermediate_levels` is a new optional form-data key, so existing saved two-column charts are unchanged and no migration is required.

Related: #20887, discussion #38713.
