### ISSUE TITLE
superset/config.py creates directory before can be overridden

### ISSUE THREAD

**Issue by laranzu** [apache/incubator-superset#3223]
Version: 0.18.5

Platform: Ubuntu 16.04 Linux with Apache 2.4

About 27 lines into superset/config.py is:
```
DATA_DIR = os.path.join(os.path.expanduser('~'), '.superset')
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

```
which will try to create the directory before it can be overridden by a new value in superset_config.py. If the program does not have permission to create the directory, superset will crash.

Example: when superset is run from Apache via mod_wsgi, it attempts to create /var/www/.superset and crashes.

**Comment by mistercrunch** [comment]
I feel like it's pretty common practice for application to do this. Shouldn't users have access to their home?

Though I agree that if the user sets a different home for the configs we should just use that.

**Comment by mistercrunch** [comment]
If someone wants to add support for a `SUPERSET_HOME` env var I'll be happy reviewing the PR

**Comment by laranzu** [comment]
I raised this issue because superset/config.py specifically says:
All configuration in this file can be overridden by providing a superset_config
in your PYTHONPATH

**Comment by leorochael** [comment]
Looking `superset/config.py`, I see no reason why `DATA_DIR` needs to be created so early.

None of the uses inside the `config.py` file actually require that `DATA_DIR` exist before `config.py` itself finishes loading.

This indicates that it should be fairly safe to move its creation after the point where `superset_config` is imported.

The caveat is that any code inside `superset_config.py` should also either assume `DATA_DIR` will only exist after `superset_config.py` is finished loading or it should create `DATA_DIR` itself.

While #3238 allows an environment variable to point `DATA_DIR` to a writable location, providing a workaround for this issue, I think it's still valuable to allow `superset_config.py` to override it so that setting an(other) environment variable is not required.

If you agree, I can create a PR.

**Comment by leorochael** [comment]
> Please send a PR.

Done: #4143
