### ISSUE TITLE
[sql lab] issue around async results fetching while changing tabs

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3290]
If you're hoping around tabs while your async query finishes, the fetching never happens, you stay stuck at 100%, `success`, and no results are shown.

**Comment by tmccartan** [comment]
We're still having this issue with long running queries on 0.29.0rc7 when using a celery/redis backend.

**Comment by dflionis** [comment]
Same issue here. Here are some more details in case any of these help:

If we run Query A on Tab 1 and then Query A on Tab 2 moments later, the tab that finishes first successfully returns the results to the screen while the other tab stays stuck at "100% success" and doesn't render. If we then run Query A on Tab 3 it will render successfully while the stuck tab remains stuck.

Using multiple browser tabs instead of multiple Superset tabs appears to be a workaround.

We also didn't notice this behavior until we moved from synchronous to asynchronous queries.
