### ISSUE TITLE
why # Timeout duration for SQL Lab synchronous queries SQLLAB_TIMEOUT  optine is not effective

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#3320]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Could you please stop opening issues just because you can? Use the mailling list or gitter for support questions. Timeouts are already being discussed here https://github.com/apache/incubator-superset/issues/3030 no need to open random issue. Please close this and the other issue you opened recently.
