### ISSUE TITLE
Auto email dashboard on predefined date and time, is this possible ?

### ISSUE THREAD

**Issue by aakulks** [apache/incubator-superset#3393]
Hi All

I am using superset version 19.
I am new in Superset, Currently searching auto mail facility in superset. Any body have any idea, please let me know.

Aakulks

**Comment by xrmx** [comment]
You should be able to implement it if you need it.

**Comment by jackpgao** [comment]
We want the same feature.

**Comment by kingo55** [comment]
Have thought about this myself - May not be the most practical, but would a
headless browser initiated via crontab do the job? That would allow you to
capture all charts and tables on a dashboard. Meanwhile crontab is very
flexible with scheduling.

Any tools to regularly screenshot web pages would do too. e.g.
https://www.stillio.com/

Don't see how else dashboards / graphics can be generated serverside since
all the charts are rendered client-side in the browser.

**Comment by masterlittle** [comment]
Maybe phantom.js could be of help? Though it would also be client side rendering I guess. Haven't taken much look at it

**Comment by jackpgao** [comment]
We use python to take a capture of the dashboard, and send it with HTML.

It not so good, but it works.

**Comment by jimanvlad** [comment]
I'm also interested in this, as it's one of the main features we use in Tableau currently.

**Comment by SpyderRivera** [comment]
@jackpgao I am looking at implementing this feature. What are the issues with python capture? Resolution?

**Comment by jackpgao** [comment]
@SpyderRivera 

Hi, use phantomjs to capture the whole Dashboard to a picture, then put it to an HTTP server dir, and you can visit the pic via a browser. In the end, you send an email with HTML format and the receiver can view the pic via email.


But there are 2 things to concern:

One is to force refresh the dashboard, cause superset use cache.

The other one is that, if the height of the pic is very long, in some email client it may crash, such as outlook, but with the Mac email client, it's ok to show the big pic.
