### ISSUE TITLE
Deleting filters clears all following filters

### ISSUE THREAD

**Issue by joshwalters** [apache/incubator-superset#3429]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.19.1

### Expected results

If there are 2 or more filters in a slice, removing a single filter should leave the other filters unaffected.

### Actual results

If a user deletes (clicks on the "-" button) a filter, all the filters below will go empty. 

### Steps to reproduce

Make a slice with a 3+ filters on different columns. Remove the top filter. You should see that the following filters are now empty.

**Comment by Mogball** [comment]
The bug seems to be the result of how the UI widgets are handled. 

Clicking the remove button will modify the prop `value` of `FilterControl` but the `Filter` components are not updating the choices for their value selection boxes. The filters appear cleared on the UI (but are actually still in effect) because the value selection box will not display the selected values if they conflict with the available choices. 

Triggering a refresh, e.g. by selecting a column in the filter, will properly display the widget. 

I've managed to solve this issue by storing the selection choices for each filter in `FilterControl` instead of `Filter`, making AJAX calls only when a filter column changes or when adding a new filter, and passing these choices as props.

**Comment by xrmx** [comment]
@Mogball PR welcome!

**Comment by joshwalters** [comment]
Merging https://github.com/apache/incubator-superset/pull/3458 fixed this issue.

**Comment by xrmx** [comment]
Thanks for the heads up!
