### ISSUE TITLE
High availability configuration documentation

### ISSUE THREAD

**Issue by SNVSNANNAPA** [apache/incubator-superset#3448]
Is there any way to run the superset in high availability environment ? like common configuration in one instance and processing in another/multiple instances. I can't find the documentation related to this.

**Comment by mistercrunch** [comment]
You can start as many web servers and Celery workers as you'd like. It's all stateless so it just works.

At Airbnb we run it as 2 namespaces in Kubernetes, one for the web servers and one for the workers so that we can scale them independently.

From my experience different companies have very different (but similar) ways to run their services (chef, puppet, ansible, kubernetes, docker swarm, ...) so it's hard to generalize anything.

We should make it clear in the docs that you can just start as many instances as needed.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 220 days. Feel free to comment and request for this issue to be reopened.
