### ISSUE TITLE
Apply time filtering to "time grain" truncated dates

### ISSUE THREAD

**Issue by nbonnotte** [apache/incubator-superset#3538]
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

v0.19.1

### Expected results

Say I want to display the number of items purchased per week over the last 3 months with a bar chart. I choose a weekly time grain, and set the time window to start from "90 days ago"

![image](https://user-images.githubusercontent.com/9929982/30907043-ed8dcffe-a379-11e7-9104-05a552ddd3b9.png)

I would expect the first bar, for the first week, to correspond to the number of items purchased for the whole week, not for the part of that week that happen to be within the 90-day time range.

```sql
SELECT DATE_TRUNC('week', purchase_timestamp) AS __timestamp,
       COUNT(*) AS purchases
FROM purchase_table
WHERE DATE_TRUNC('week', purchase_timestamp) >= DATE_TRUNC('week', TIMESTAMP '2017-06-29 00:00:00')
  AND DATE_TRUNC('week', purchase_timestamp) <= DATE_TRUNC('week', TIMESTAMP '2017-09-26 00:00:00')
GROUP BY DATE_TRUNC('week', purchase_timestamp)
```

### Actual results

The first bar is truncated, and does not correspond to the whole week

```sql
SELECT DATE_TRUNC('week', purchase_timestamp) AS __timestamp,
       COUNT(*) AS purchases
FROM purchase_table
WHERE purchase_timestamp >= '2017-06-29 00:00:00'
  AND purchase_timestamp <= '2017-09-26 00:00:00'
GROUP BY DATE_TRUNC('week', purchase_timestamp)
```

**Comment by mistercrunch** [comment]
I agreed that this is the desired behavior to get "full buckets"

**Comment by nwang57** [comment]
I also found an issue with `literal_column` from SQLAlchemy that will escape the "%" symbol in the string. The final SQL will have two consecutive "%".
<img width="879" alt="screen shot 2017-12-22 at 8 00 51 pm" src="https://user-images.githubusercontent.com/7065997/34315783-0e75e68a-e753-11e7-91cf-4bfcc12dc07d.png">

This issue is related to #617 . I tried to switch to the SQLAlchemy 1.2.0b3 and it works fine. So they already fix this issue in the latest version.
