### ISSUE TITLE
Creating user by api

### ISSUE THREAD

**Issue by AnithaMurugesan** [apache/incubator-superset#3602]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.19.0

I want to create the new users by api.
The api endpoint for creating user is /users/api/create
But passing the curl command asks for csrf token.I have passed the csrf token value along with data and also with headers. But "The CSRF token has expired." error occurs.I can also find that the csrf_token value keeps on changing.

I have also made WTF_CSRF_ENABLED = False
But the same error continues.

What is the format to create user by api??
Is there a way to create users without using csrf_token??

**Comment by mistercrunch** [comment]
There's also `WTF_CSRF_EXEMPT_LIST` you might want to try, though I haven't used it personally. `WTF_CSRF_ENABLED` should really work, if not that's a bug that needs to be addressed. Are you sure that your config is set properly and gets picked up? When you start your web server the very first line should be something that looks like
```
Loaded your LOCAL configuration at [./pythonpath/superset_config.pyc]
```

At Airbnb we use the ORM as an API since we're writing things in Python.

**Comment by AnithaMurugesan** [comment]
Thanks.
"Loaded your LOCAL configuration at [./pythonpath/superset_config.pyc]" -- Yes...I can find this line on starting superset service.
"At Airbnb we use the ORM as an API since we're writing things in Python." -- Does this mean ,it is impossible to create user by api??
