### ISSUE TITLE
URL Prefix Superset Flask

### ISSUE THREAD

**Issue by abhisharma7** [apache/incubator-superset#3690]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset-0.20.4

### Expected results
Want to run superset on http://127.0.0.1:8088/analytics/ , currently it runs on http://127.0.0.1:8088. Although, I understand this is not a bug but there should be a way in configuration file (config.py) to change url_prefix. When I am moving my superset installation to Production, I would prefer to keep it behind the proxypass of apache and not expose it directly on /.  

### Actual results
I couldn't find any option in config file to change the url_prefix in flask.

### Steps to reproduce
Its a default setting. Need an option in config file or a procedure to add url_prefix. 

Thanks

**Comment by geekSnails** [comment]
I meet the same problem

**Comment by raditsp** [comment]
:+1:

**Comment by movekj** [comment]
@geekSnails +1

**Comment by michailsal** [comment]
+1

**Comment by lambdaq** [comment]
basically, no

https://github.com/apache/incubator-superset/pull/1866/

This PR was closed after 3 months... Sad.

**Comment by kirankumarpv** [comment]
Hi, 

I am also having the same issue. I tried to fix it using Blurprints but superset doesn't seem to take into consideration blueprints with url_prefix. 

The main reason the need for me is I am trying to deploy superset on AWS Lambda on a serverless environment and since AWS API Gateway adds a stage name like '/dev' all the links are broken. I am able to get to the login page but most of them doesn't work because it seems it's trying to access resources at "/" but API Gateway puts all of them at "/dev". 

Any other way or do we need to modify all the static URL's? 

Can you help me to see if someone can get Blueprints working on superset with url_prefix option? 

Thanks

**Comment by sshcherbakov** [comment]
Just a feedback here.
This is a shame that such basic functionality doesn't work because of the code quality (and subsequent difficulty to fix).
The workaround in the [PR #1866](https://github.com/apache/incubator-superset/pull/1866) is ugly and doesn't really work. It relies on the reverse proxy config (which might not be appropriate in some cases) and still requires Superset to run on the default root context path ('/').
:(

**Comment by pdoto** [comment]
Hi all, i have been working on the same issue for a while and i have some suggestions,
like @sshcherbakov  mentioned the only way to workaround is to rely on reverse proxy configuration which is not very appropriate, you will end up with a configuration like this:
```
location ~ ^/(users|userstatschartview|roles|permissions|permissionviews|viewmenus|logout|login|logmodelview|dashboardasync|databaseasync|csstemplateasyncmodelview|druid|druidclustermodelview|druiddatasourcemodelview|csstemplatemodelview|csvtodatabaseview|sliceaddview|dashboard|chart|databaseview|tablemodelview|queryview|annotationlayermodelview|annotationmodelview|lang)/ {
    		auth_basic off;
		rewrite ^/(.*) /MY_PREFIX/$1 permanent;
    		proxy_pass http://MY_ADDRESS:MY_PORT;
    		proxy_set_header Host $host;
	}
```
as you can see you need to match all the hard codded path that are being redirected to the  default root context ('/'). i will say this is ugly. There might be some further modifications in these paths which make the maintenance not very interesting.
1- The first solution i'm proposing is to make all the routes uniform by adding **/superset**, then you can rewrite the URL in nginx configuration like this:
```
location ^~ /MY_PREFIX/ {
    		auth_basic off;
    		proxy_pass http://MY_ADDRESS:MY_PORT;
    		proxy_set_header Host $host;
	}
		
	location ^~ /superset/ {
    		auth_basic off;
		rewrite ^/superset/(.*) /MY_PREFIX/superset/$1 permanent;
    		proxy_pass http://MY_ADDRESS:MY_PORT;
    		proxy_set_header Host $host;
	}
```
this is working well as long as all the paths start with  **/superset**, but because there are many other paths that does you have to match all of them like mentioned above. Even if it will still be hard coded at least it will make the workaround much easy to maintain and reliable.

2- And the second which might be less easier but good for long term is to define a global parameter configuration in the config file like (**URL_PREFIX**), which should be added as **base path** to all the routes, then get rid of the hard coded URL. 
But  even if there is still hard codes like redirects make sure to add the base path to it.
This issue is been open for 2 years now and i really hope it can be fixed.

Thanks.

**Comment by dominijk** [comment]
@pandamien I've attempted your first option to configure as below;

```
location ~ ^/(users|userstatschartview|roles|permissions|permissionviews|viewmenus|logout|login|logmodelview|dashboardasync|databaseasync|csstemplateasyncmodelview|druid|druidclustermodelview|druiddatasourcemodelview|csstemplatemodelview|csvtodatabaseview|sliceaddview|dashboard|chart|databaseview|tablemodelview|queryview|annotationlayermodelview|annotationmodelview|lang)/ {
    		auth_basic off;
		rewrite ^/(.*) /dashboard/$1 permanent;
    		proxy_pass http://MY_ADDRESS:MY_PORT;
    		proxy_set_header Host $host;
	}
```


 but i just end up with endless redirect as;

http://wesbsite/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/dashboard/login/ 

Have I missed something obvious?

**Comment by dominijk** [comment]
Theres an interesting looking option on [Stackoverflow](https://stackoverflow.com/questions/45864887/setting-up-apache-superset-with-nginx-as-reverse-proxy)  which I'm trying to set up

**Comment by kirankumarpv** [comment]
Hi, 

I wanted to run 'Superset' in complete serverless environment on AWS. Basically, want to run superset on AWS Lambda. 

I have tried different methods recommended and all of them resulted in some or other place break of functionality. Eventually what i did was the below to make it work: 

1) In config.py i have added another configuration variable and used this variable in locations where redirect or appbuilder.add_link has been used.
2) In templates folder there are places where directly '/superset/' has been used. So, even if i did first step right, the templates are not rendering in right way. So, i have to go and change the template as well (As of now I have hard-coded this. I need to make it configurable) 
3) In front-end i have added a file called config.ts and I have used this config in locations wherever redirect was done in front-end. This has fixed up all my front-end links. 
4) Only thing remaining for me was fixing "Upload CSV to Database" Link.  When we click this link and enter the data, since Lambda doesn't allow any writes i tried to write to /tmp - but since we don't know whether the next request is going to be served by same lambda or not... so this is an issue as of now. The way I am planning to fix this is to write the files to s3 instead of local folder. I am still figuring out a way to do this. 

After above all are done, I have used AWS Aurora Serverless as my metadata database. This way I don't even need to pay for the database since Aurora is MySQL version. 

Hope this helps. Once i fix up the remaining this, I need to check how to make this available to all. 

Thanks
Kiran

**Comment by dominijk** [comment]
@kirankumarpv I'd be very interested in an update on this as I was about to attempt the same thing.

**Comment by kirankumarpv** [comment]
> @kirankumarpv I'd be very interested in an update on this as I was about to attempt the same thing.

All the fixes has been done and tested directly on AWS Lambda. Everything working fine.

**Comment by kirankumarpv** [comment]
Hi, 

Can anyone help me to make a pull request for this particular issue so that i can merge the code? 

Thanks

**Comment by alikefia** [comment]
I am facing the same problem.
This is due to absolute redirection (not using `url_for`)
example: https://github.com/apache/incubator-superset/blob/master/superset/__init__.py#L191
Workaround: wsgi middleware to catch redirection response and dirty patch Location HEADER
Sorry, no time immediately to propose a PR

**Comment by kirankumarpv** [comment]
> I am facing the same problem.
> This is due to absolute redirection (not using `url_for`)
> example: https://github.com/apache/incubator-superset/blob/master/superset/__init__.py#L191
> Workaround: wsgi middleware to catch redirection response and dirty patch Location HEADER
> Sorry, no time immediately to propose a PR

I have tried that. Using wsgi middleware to catch redirection reponse and dirty patch location HEADER but that results in sometimes application going to indefinite multiple redirects

**Comment by chethanMRP** [comment]
Hi Kirankumar,

I was seeing you comments on your success of implementing Superset on AWS Lambda. I was struggling to get any literature for doing the same. Can you please guide me to do this.

Regards,
Chethan G Puttaswamy

**Comment by psykidellic** [comment]
Can this be reopened as a feature request? we would like to use it but not able to run it on a subpath /superset makes it impossible to use it in our environment. I have been able to run it using the helm chart but not being able to run a subpath makes it a non starter for me.

**Comment by thammaneni** [comment]
Hi Team,

Do we have fix for this issue in latest 0.36 version?

Thanks.

**Comment by alikefia** [comment]
Hello @thammaneni,
I don't think so since there is still "hard" redirections (path vs url_for)
Example : https://github.com/apache/incubator-superset/blob/master/superset/views/core.py#L496
++ / Ali

**Comment by cdmikechen** [comment]
I forked and opened a new branch to support URL Prefix by `/superset`, https://github.com/cdmikechen/incubator-superset/tree/0.38-syzh . 
I have add some custom class extend `flask-appbuilder` class and change superset rest api blueprint. If anyone is interested, we can communicate with each other.

**Comment by Moofasax** [comment]
Any updates on this?

**Comment by mrgokul** [comment]
+1, this is a very useful feature. @cdmikechen does this still work the latest release of superset?

**Comment by cdmikechen** [comment]
@mrgokul You can look at this https://github.com/apache-superset/superset-roadmap/issues/105
I've add it in version 1.0.1 and test for a month. The python codes change between 0.38 and 1.0.1 are not too big, so they can be directly used as reference. I think I'll open a pr some time later.

**Comment by syazwan0913** [comment]
Is it possible to use Nginx to rewrite the URL using latest Superset?

**Comment by mrgokul** [comment]
> @mrgokul You can look at this [apache-superset/superset-roadmap#105](https://github.com/apache-superset/superset-roadmap/issues/105)
> I've add it in version 1.0.1 and test for a month. The python codes change between 0.38 and 1.0.1 are not too big, so they can be directly used as reference. I think I'll open a pr some time later.

Awaiting your PR!

**Comment by andrey-mikhailov** [comment]
I had the same issue. I had to add url prefix to all routes in python and js files. The patched Superset version is here https://github.com/andrey-mikhailov/superset-custom-path

**Comment by grameshtwilio** [comment]
Hi @andrey-mikhailov , Any chance you can create a PR for (the fix after running your script) and ask an admin to approve?

**Comment by mrgokul** [comment]
Hi @andrey-mikhailov , Any chance you can create a PR for (the fix after running your script) and ask an admin to approve?

**Comment by andrey-mikhailov** [comment]
Superset community will never accept this implementation, custom url path should be done in more robust way

**Comment by parked-toes** [comment]
I would be fine, at least, if all sub-pages have /superset prefix. Currently, it's very inconsistent.
E..g /dashboard/list
     /superset/dashboard

**Comment by SimonKlausLudwig** [comment]
Its a shame that this is not possible. I set up superset, everything is great and now i need to stick to something else as i cant integrate it into our app.

**Comment by villebro** [comment]
FWIW, I'm sure the community is open to review a PR that adds this functionality.

**Comment by alikefia** [comment]
The issue identified, years ago, is hard coded urls in the code (https://github.com/apache/superset/blob/master/superset/views/core.py#L297).
The idea is to track them and use `url_for` that will build the effective URL based on the global configurations.

**Comment by villebro** [comment]
> @villebro Hi~ where is the PR? I want to see it~

@cdmikechen to rephrase, if this feature is important for the community, feel free to open a PR that adds the functionality. But keep in mind: for it to get merged it needs to be of high quality in general (abide to best practices generally recommended by the used libraries/frameworks) and include good tests.

**Comment by Step1N** [comment]
> Theres an interesting looking option on [Stackoverflow](https://stackoverflow.com/questions/45864887/setting-up-apache-superset-with-nginx-as-reverse-proxy) which I'm trying to set up

By setting up ADDITIONAL_MIDDLEWARE it working for some routes, for statics need to bypass it.

**Comment by mskimm** [comment]
I tried reverse proxy. I haven't checked that all the rules have been added, but most of them seem to work.

https://github.com/mskimm/prefixed-superset

**Comment by ralberich** [comment]
Thanks @mskimm , it definitly works with docker, but tried to make it work using manual install with gunicorn / superset in an env, somehow it works, but referer and links in the page doesnt get rewritten. Any idea what could cause that?

**Comment by mskimm** [comment]
Is there nginx in front? If so, there doesn't seem to be difference between manual installation and docker.

**Comment by RoBYCoNTe** [comment]
> I tried reverse proxy with sub_filter. I haven't checked that all the rules have been added, but most of them seem to work.
> 
> https://github.com/mskimm/prefixed-superset

You literally save my life, in next days I will try all routes and add what is missing, right now I can confirm that your solution is the only one working with the application subpath configuration.

**Comment by 596192804** [comment]
> I tried reverse proxy with sub_filter. I haven't checked that all the rules have been added, but most of them seem to work.
> 
> https://github.com/mskimm/prefixed-superset

Thanks a lot!!!

**Comment by v9dev** [comment]
I changed the code both frontend and backend and it is woking without superset  if anyone want I can upload into my github.
