### ISSUE TITLE
Set up eslint eslint-plugin-prefer-object-spread

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3835]
We prefer spread over `Object.assign`. Looks like there are 162 entries to clean up...
```
22:07 $ git grep "Object.assign" | wc -l
     162
```

**Comment by rsn491** [comment]
This issue was tackled in #9466 
The remaining 6 `Object.assign` occurrences at [master](https://github.com/apache/incubator-superset/commit/5e4c2919135e284c50a4bdeb1ecff54514804a6b) seem to be compliant with the [prefer-object-spread](https://eslint.org/docs/rules/prefer-object-spread) rule. 

Should this issue be closed?
