### ISSUE TITLE
Is possible to use one dashborad with multiples data sources 

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-superset#3874]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.20.4

### Expected results
Only one dashboard with multiple data source which can change for specific users.

**Comment by mistercrunch** [comment]
Dashboards can have a slices that have different underlying datasources.

Datasources won't change based on users though, I'm not sure what you're trying to accomplish with that. Some row-level security hack using views?

**Comment by amoussoubaruch** [comment]
Thanks @mistercrunch 

It is a good way to do it. 
I will create for each datasource one groupe permission to access to dashboard. I thinks it's enough for my use case.

**Comment by amoussoubaruch** [comment]
@mistercrunch 

I try this but it's dont work. Please let me explain : I create a dashboard with  one datasource and i want to use same dashboard with another datasource. When i edit Associated Slices for the new datasource by adding all slices i created, for the first data source all slice are deleted. 
Can do something like that please?

**Comment by xrmx** [comment]
You should add new slices, not removing the old one.

**Comment by amoussoubaruch** [comment]
I don't remove old slices. That is what i do : 

1. I create a dashboard with datasource1. (For country 1) : so i have 5 slices associates
2. I have now another datasource2 (for country 2) that have same dimensions and metrics.

I don't want to create another dashboard for this country but use same dashboard.

**Comment by amoussoubaruch** [comment]
@mistercrunch how can do this "Dashboards can have a slices that have different underlying datasources"?

**Comment by nirvanesque** [comment]
@mistercrunch + @xrmx : Hello, amoussoubaruch is working with me, please allow me to chip-in :-)

What we want to achieve is something like this:

1. We have two différent datasources: ds1 and ds2, both are Druid datasources, and their columns / dimensions are identical. Only the content (rows) is different. For privacy reasons, we cannot keep the two content in the same datasource. 
2. There are 3 groups of users: g1 that may see/access ds1 ONLY, g2 that may see/access ds2 ONLY, and, g3 that may see/access both g1 and g2. 

The problem is stated with just 2 datastores, but in reality we have some ~100 datastores. Hence, our objective below.

Objective: To avoid duplication of dashboards and slices, as much as possible. i.e. To have a single dashboard with same / identical slices, which, 
- when viewed by group g1 will show the contents of ds1, 
- when viewed by group g2 will show the contents of ds2, and,
- when viewed by group g3 (at login) will show as 2 accessible dashboards - with content from ds1 and ds2 (or at worst, a single dashboard that shows the combined content of ds1 and ds2).
This is especially 

Question 1 -feasibility : Is this first of all possible to do in some way or the other ?
Question 1a : If feasible, how would you go about doing this ? Please give us some concrete guidelines to work on.
Question 2: does the a

Please let us know if the problem is clearly understood.

We are happy to share the results (either blog or a merge request - as necessary).

For us (a big data labs) Superset stands out clearly as an advanced DataViz/Reporting framework, far ahead of notebook-based or traditional tools. 
We are trying to evangelise it within our users. Please help us in this.

Thanks in advance !

**Comment by xrmx** [comment]
Thanks for clarify the request, but this is a duplicate of https://github.com/apache/incubator-superset/issues/3608
