### ISSUE TITLE
Choose dimension to split with at the dashboard level

### ISSUE THREAD

**Issue by AxelDelmas** [apache/incubator-superset#3962]
We are in a situation where we want to split the exact same dashboard with a different dimension depending on what we're testing.
Right now the only solution we've found is to duplicate every slice in the dashboard, change the dimension we use to split data for every single slice, and recreate a new dashboard with all these new slices.
It is very time consuming, and it is quite hard to keep all these dashboard up-to-date as we add metrics in a slice and so on.

It would really save us a lot of time if we could have a single dashboard and choose which dimension(s) we split the data on at the dashboard level.
A way to acheive this would be to add an (optional) "split" field in the filter slice, in which we could specify which dimensions we want to split data on for all the slices in the dashboard

**Comment by mistercrunch** [comment]
There are a few challenges around this but it's on the roadmap. While the "Filter Box" slice type is useful, it's pretty limited in what it can do and I've been thinking it needs to be re-written in a more generic way. Currently for instance it does not allow for per-dimension-configuration (all dims are based off the same metric for instance and sorted based on the same rule).

We need a more generic "dashboard controller" dashboard section or viz type. Folks at Airbnb are re-designing the whole dashboard app so that it can have nested "scoped" sections, tabs, filters that apply only to sub sections, ... Many of these dashboard components shouldn't be modeled as a visualization types but instead as dashboard primitives. 

Note that dashboard-level controls are in scope I think, meaning bringing a "GroupBy" control (or any other control) to a dashboard section can affect many charts.

@williaster can you share your mocks?

**Comment by williaster** [comment]
I believe Eli is working on the mocks, will post or get him to once they're done (likely next week)

**Comment by elibrumbaugh** [comment]
@mistercrunch will share as soon as we have something worked up next week.

**Comment by AxelDelmas** [comment]
Awesome, glad to hear this is in the works! Would definitely appreciate if you can share the mockups once you have a first version to show

**Comment by Csnigs** [comment]
Great to hear it's on the roadmap indeed! The "scoped" dashboard section would be a dream come true to be honest. Here is a list of the limitations we tend to bump into on top of the "dimension split on the dashboard level" if that helps you in any way with the design:
- Mixing various data sources in one dashboard is doable but difficult since Filter Box will apply to all slice (so if the filtered dimension is not in one of the datasource, those slices won't display any data)
- We have a few sets of filters that we want to apply to a group of slices only, which atm forces us to reload the entire dashboard when we use the Filter Box (which can be pretty heavy if you don't take precautions)
- The per-dimensions-configuration would indeed be a nice addition
- We have ~15 dimensions on which we regularly apply filters so we had to break the Filter Box in smaller ones to allow for fast load of the Filter Box itself (the first filter box only contains the time filtering and our main dimension, the second ones contains more advanced dimensions, and a third only contains dimensions that are rarely used). This is working fine but require a bit of juggling with `Apply` button and FilterBox `Force Refresh` Button.

Don't hesitate to ask for more details if you need. Thank you!

**Comment by mistercrunch** [comment]
Great feedback. A few other notes:
* loading different dimensions could be parallelized on the backend to make things faster
* cascading filters (where the list of values is based on a previously selected filter) are great for hierarchies (think: continent->country-> city). Currently it's doable only by having multiple FilterBox slices where one refreshes based on the other, but not the other way around (you can make the first filterbox immune to filtering). It's pretty common for BI tools to know about hierarchies and we could add support for that in our semantic layer and cascade things accordingly based on that.

**Comment by colax94** [comment]
Hello, is there any news around this ?

**Comment by junlincc** [comment]
@colax94 we are gradually rolling out features like native dashboard filter(by columns/dimensions, range, time) and group-by. 
Most of the features are in development under feature flags.

**Comment by emeraldic** [comment]
Hello, any news?

**Comment by mvsenin** [comment]
Hello everyone,

I'm not sure it helps, but we actively use URL params for data filtering. Firstly, it's necessary to design your data model since this approach applies using Jinja's {{url_param()}} in dataset SQL queries. So, each or almost each chart of you dashboard(s) should be using a dataset with corresponding conditions in the WHERE clause, e.g.

WHERE YourDimension = '{{url_param('DimensionName')}}'

Finally, your dashboard(s) can be invoked with the param in its URL, say:

htttps://TheServer/DashboardSlug/?DimensionName=DimensionValue

So, the condition below will be translated to the something like that:

WHERE YourDimension = 'DimensionValue'.

Please read Jinja docs, maybe that can help.

Wish you luck.
