### ISSUE TITLE
Need for Fiscal Year (rather than Calendar Year) in visualizations.

### ISSUE THREAD

**Issue by GITBoston** [apache/incubator-superset#4012]
I can't get Pivot Table and other visualizations to work with my organization's fiscal year. Our year closes 9/30 not 12/31. I imagine many/most organization will have this problem. 
Is there a workaround? Or should this be feature request?

**Comment by TryHarder01** [comment]
Does querying a different date range solve the problem for you?

**Comment by Waffle-Meister** [comment]
I think the issue is with any of the time series visualizations.  Even if you set the query to only capture the fiscal year, it will leak into another year on the time axis. For example:

![image](https://user-images.githubusercontent.com/34284871/33629004-8cb3fde2-d9d0-11e7-9ca0-9acb6395e2b7.png)

The data starts at fiscal year 2015 (10/1/14 to 9/30/15), but the time axis will split some into the 2014 bucket. It would be nice to have a built in offset for things like this. Though I'm not sure where the best place to put it would be.

It's misleading for business folks when they see 2014, because they're thinking fiscal year. It breaks down even worse when you make the time grains quarters and months.

My current work around is having fiscal year as a string and using the **distribution** bar chart (instead of the time series) to show the years over time. But that only works for years, and also doesn't allow the use of line charts and the other cool time series visualizations.
