### ISSUE TITLE
Oracle "ORA-00907: missing right parenthesis" error

### ISSUE THREAD

**Issue by georgek** [apache/incubator-superset#4058]
### Superset version
0.22.1

### Expected results
SQL is executed on the database

### Actual results
Error output from Oracle:
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00907: missing right parenthesis

### Steps to reproduce
Seems to happen with any query. A regression introduced since ~0.20.  I can try a git bisect later if necessary.

**Comment by xrmx** [comment]
git bisect would be very helpful, thanks!

**Comment by nichobbs** [comment]
This seems to be due to Oracle not liking the concatenation of the 'T' into the timestamp in the generated boundary dates e.g.:

AND created <= TO_TIMESTAMP('2017-12-15T05:49:48', 'YYYY-MM-DD'**T**'HH24:MI:SS.ff6'))

I extracted the SQL from the log and put it in SQL developer which gives me an error at the intermediate T.

I'm sorry I'm not in a position to take a look at the code and provide a PR at the moment but hopefully this will help someone to fix it as I'm experiencing the same issue :)

**Comment by nichobbs** [comment]
Fix appears to be to change line 1076 of superset/db_engine_specs.py to 
"""TO_TIMESTAMP('{}', 'YYYY-MM-DD"T"HH24:MI:SS.ff6')"""
from 
"""TO_TIMESTAMP('{}', 'YYYY-MM-DD'T'HH24:MI:SS.ff6')"""

Note different quotes around the T. I've made a change locally and this seems to work.

**Comment by xrmx** [comment]
Thanks for the PR! I have no Oracle clue but given the patch fixes things for you it looks good to me. Would be cool to add a test though for that method.
