### ISSUE TITLE
Integrity error while adding tables with same name, different schema in Redshift

### ISSUE THREAD

**Issue by shahneil88** [apache/incubator-superset#407]
Hi,

I upgraded to `0.8.9`
I am trying to add tables with same names in different schema (Ref #356 )
I get this error.

![screen shot 2016-04-28 at 12 02 47 pm](https://cloud.githubusercontent.com/assets/7529421/14875094/7fc77c90-0d39-11e6-893a-a1f0ac69e99b.png)

**Comment by shahneil88** [comment]
@mistercrunch - Were you able to reproduce the issue ?

**Comment by wil5for** [comment]
I'm getting the same error when adding the same table name from 2 different databases.

`2016-05-06 22:11:38,213:WARNING:flask_appbuilder.models.sqla.interface:Edit record integrity error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: tables.table_name [SQL: u'UPDATE tables SET changed_on=?, table_name=?, main_dttm_col=?, description=?, database_id=?, user_id=?, changed_by_fk=? WHERE tables.id = ?'] [parameters: ('2016-05-06 22:11:38.211673', u'my_table_name', u'', u'', 2, 1, 1, 5)]`

It looks like this migration: `b4456560d4f3_change_table_unique_constraint.py` doesn't work for sqlite. 

I was just testing with sqlite so I'll probably move to another db.

**Comment by shahneil88** [comment]
@wil5for - Does it work for other db?

**Comment by wil5for** [comment]
Confirmed it works with postgres 9.3 instead.

**Comment by pjungwir** [comment]
We're hitting this error too. It looks to me like the problem is from the migration named `b4456560d4f3_change_table_unique_constraint.py`:

```
def upgrade():
    try:
        # Trying since sqlite doesn't like constraints
        op.drop_constraint(
            u'tables_table_name_key', 'tables', type_='unique')
        op.create_unique_constraint(
            u'_customer_location_uc', 'tables',
            ['database_id', 'schema', 'table_name'])
    except Exception:
        pass
```

This tries to drop the old constraint on just `table_name`, but fails on sqlite which doesn't know how to drop constraints. (You need to [create a new table, copy everything over, drop the old table, then rename the new table to the old name](https://stackoverflow.com/questions/1884787/how-do-i-drop-a-constraint-from-a-sqlite-3-6-21-table).) So you are left with the old constraint, and never add the new improved one.

This code also shows why the problem doesn't happen in Postgres: there the migration succeeds, so the old too-restrictive constraint is dropped.

**Comment by embatbr** [comment]
Same problem on PostgreSQL 9.6. I have two tables with same name in different schemas.

**Comment by mistercrunch** [comment]
@embatbr you'll have to delete one of the two tables and re-run the migrations
