### ISSUE TITLE
How can I  only authorize users to dashboards?

### ISSUE THREAD

**Issue by ouyang-lunxi** [apache/incubator-superset#4127]
### Expected results
I want create a role only the given dashboard can be shown to him, but I can only limit his access on datasource. In another word, I want to create 2 or more different dashboards based on the same datasource, and a specified user can only see one of them. But I can't do that based on the existing security model. Is there any suggestions?

**Comment by rahulsingh303** [comment]
Create user and the assign roles . You can start with Gamma , and create additional roles with custom access to data source.

**Comment by mcdavey17** [comment]
I don't think data source access is sufficient.  ouyang-lunxi says he has two dashboards based on the same data source, and wants to provide (I presume read-only) access to one of those two dashboards.  Duplicate of #1799?

**Comment by mistercrunch** [comment]
For now security restrictions are on a per-datasource only (also, per schema and per database), allowing users to drill-through and slice/dice the data behind the dashboard.

We do understand the use case where the user may be allowed to see a dashboard, but not to explore the underlying datasources and are planning on supporting this at some point.

**Comment by LanDeQuHuXi** [comment]
+1 read-only public dashboard would be nice

**Comment by mojitodaiquiri** [comment]
+1 read-only public dashboard would be nice

**Comment by TianyangLi** [comment]
@LanDeQuHuXi @mojitodaiquiri i think that functionality is in the works:
https://github.com/apache/incubator-superset/pull/4725

**Comment by cscainiao** [comment]
@isunix Can you elaborate on the implementation steps? Thank you

**Comment by ug911** [comment]
Is this feature implemented?

**Comment by SonaliSihra** [comment]
is this feature is implemented? or anyone is working on it?

**Comment by startwoinformatica** [comment]
Using the reply from [@A. kyenze](https://stackoverflow.com/questions/50295010/is-there-a-way-to-create-read-only-dashboard-in-apache-superset), I had to change some permissions to enable the user to have the following permissions: 
1. Recent Activity 
2. Favorites 
3. Dashboards Lists

So I ended up having the permissions bellow: 
`[can list on DashboardModelViewAsync, can dashboard on Superset, can fave dashboards on Superset, can recent activity on Superset, can favstar on Superset, can explore on Superset, can fave dashboards by username on Superset, can csrf token on Superset, can explore json on Superset]`

Also had to add (of course) the datasource access rights: 
`[datasource access on [database_3].(id:3), datasource access on [database_3].table_2]`

[User Roles](https://ibb.co/58rR1G6)
[Dashboards](https://ibb.co/4VjJPtY)
[Recent Activity](https://ibb.co/ZLvssCx)
[Favorite](https://ibb.co/hV472Vn)

So, because i've a generalViewer, and another role to setup the datasource access, it's really easy to add new daashboards to different users.

**Comment by SWoto** [comment]
Using the reply from [@A. kyenze](https://stackoverflow.com/questions/50295010/is-there-a-way-to-create-read-only-dashboard-in-apache-superset), I had to change some permissions to enable the user to have the following permissions: 
1. Recent Activity 
2. Favorites 
3. Dashboards Lists

So I ended up having the permissions bellow: 
`[can list on DashboardModelViewAsync, can dashboard on Superset, can fave dashboards on Superset, can recent activity on Superset, can favstar on Superset, can explore on Superset, can fave dashboards by username on Superset, can csrf token on Superset, can explore json on Superset]`

Also had to add (of course) the datasource access rights: 
`[datasource access on [database_3].(id:3), datasource access on [database_3].table_2]`

[User Roles](https://ibb.co/58rR1G6)
[Dashboards](https://ibb.co/4VjJPtY)
[Recent Activity](https://ibb.co/ZLvssCx)
[Favorite](https://ibb.co/hV472Vn)

So, because i've a generalViewer, and another role to setup the datasource access, it's really easy to add new daashboards to different users.

**Comment by michalmisiewicz** [comment]
@mistercrunch Is this functionality in roadmap ?

**Comment by Lemmynjash** [comment]
Hello team 
Is this feature implemented?
