### ISSUE TITLE
Dashboard Filtering Issue across different data sources

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#4169]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "e7f8143c3b4d252519bf3f826a95033578b059a1", "version": "0.23.0dev"}

### Steps to reproduce
* Create Dashboard from two table visualization slices from two different druid data sources
* Enable 'filter select' on both. Make sure the dimensions queries don't overlap with each other. 
* If the dimension that is filtered does not appear in another table, you would see 'No data was returned' error. 

### Expected results
The previous version of superset used to ignore these filters gracefully. It would be nice to have the same behavior. With SQL tables it works like this. 

### Actual results
![image](https://user-images.githubusercontent.com/391567/34660948-13105fae-f3fb-11e7-8631-9581b21c472f.png)

![image](https://user-images.githubusercontent.com/391567/34660959-210f1de8-f3fb-11e7-9032-7aac8d8a7fe9.png)

![image](https://user-images.githubusercontent.com/391567/34660970-2d420292-f3fb-11e7-8d38-b315461f04e6.png)

cc @Mogball

**Comment by kkalyan** [comment]
@john-bodley @oxydash will be able to take a look at this issue?

**Comment by john-bodley** [comment]
@kkalayn I believe this change is a side effect of the caching restructure (cc @mistercrunch) however one could argue showing ‘No data’ is more accurate than failing gracefully as users could misinterpret the results as they would be unaware that the filters weren’t functioning.

**Comment by kkalyan** [comment]
thanks @john-bodley for the response.

I personally believe graceful dashboard filtering is a better option as it gives a workaround for lack of joins in Druid. Please note for mysql data sources the graceful filtering still works and it stopped working for Druid after 0.19.1. We are not upgrading to the latest version because of this.

**Comment by Mogball** [comment]
I noticed this a few months ago. I think the logic that separated filters based on data source was lost at some point (in the JS)

**Comment by mistercrunch** [comment]
Looks like a bug, the dashboard controller should not even try to broadcast the filter to a slice that doesn't have the dimension getting filtered on. From memory the dashboard controller has all the datasources metadata and should be able to not emit the filter.

I'm guessing since Druid supports heterogenous schemas (different schemas can have different dimension sets), it recieves the filter an returns nothing...

**Comment by kkalyan** [comment]
@mistercrunch thanks. any suggestions for implementation direction? Dashboard filtering does not have many tests, I'm not confident of making changes. Appreciate your help here!

**Comment by mistercrunch** [comment]
@graceguo-supercat can you provide pointers?

**Comment by graceguo-supercat** [comment]
@mistercrunch @kkalyan I will take a look.

**Comment by bonysimon007** [comment]
Am using version 0.35.2 of the superset.  And am facing a similar issue.  

**Steps to reproduce**

- Create a dashboard with two charts and from two different data sources(tables). 
- Create a filter for any one of the charts. 
- Now apply a filter condition
- You can see both the charts are affected by the filter condition set for one chart.

**Expected Result**

Only one chart should be affected by the filter since the data source(table) is different.

**Actual Result**

Both the charts are affected irrespective charts of having different datasources.

@mistercrunch @kkalyan 

Please have a look. This issue makes it impossible to use multiple datasources in a dashboard and use filters. 

The data resides in Postgres
