### ISSUE TITLE
[Filter Box] Boolean values show up blank in selector

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4297]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Should show true/false

### Actual results
Shows blank

### Steps to reproduce
Add boolean type column to filter section

<img width="365" alt="screen shot 2018-01-25 at 7 00 35 pm" src="https://user-images.githubusercontent.com/33429480/35423349-2248398c-0202-11e8-8f6d-e460edb684a6.png">

**Comment by mistercrunch** [comment]
Presto? Redshift?

**Comment by circld** [comment]
Also experiencing this behavior on v0.22.1 Postgres tables for any BOOLEAN columns used in a Filter Box slice.

**Comment by jakromm** [comment]
I'm sure the root cause on this is different, but since you are addressing this code area it might be an easy fix.  When exploring a slice and "Enable Filter Select" is enabled, the NULL case in the drop down also shows up as Empty like is shown above.  There also doesn't seem to be a way to filter for IS NULL, if you try to use the 'in' predicate it creates an empty set and simply does 1 != 1 (or however you have empty_in_strategy configured for the connection).

**Comment by mistercrunch** [comment]
related as prerequisite: https://github.com/apache/incubator-superset/pull/4651
