### ISSUE TITLE
superset (0.22.1) export Chinese  to csv garbled

### ISSUE THREAD

**Issue by xiamujun** [apache/incubator-superset#4506]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset (0.22.1)

### Expected results
export  result like image ：

### Steps to reproduce
![image](https://user-images.githubusercontent.com/12455569/36839069-e1727d2e-1d7b-11e8-9a07-4cb1d7ddffa2.png)

**Comment by xrmx** [comment]
Could you please define garbled?

**Comment by xrmx** [comment]
@xiamujun I was asking to to describe what's wrong in the picture you posted, I can't see anything wrong in there.

**Comment by BigFaceFish** [comment]
1) look for file 'config.py' in your superset environment:
File path on my server:
/root/venv/lib/python2.7/site-packages/superset/config.py
2)search "encoding" in this file and modify that line into:
'encoding': 'gb18030',
the default encoding mode is utf-8, but default encoding in office is GB. This is the root cause.
3) restart your superset service. Good luck.

**Comment by xiamujun** [comment]
ok，thanks！

**Comment by wutengyue** [comment]
我按照 @BigFaceFish 说的，修改了'config.py'中的'encoding'，重启服务，但是不起作用。
导出的csv文件的编码依然是utf-8，你知道是什么原因吗？
