### ISSUE TITLE
Allow defining roles in config file

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#479]
As a data structure. Most likely a dictionary where the key is the role name, and the value is a dictionary with the following keys:

``` python
roles = {
    'myrole': {
         'based_on': 'Alpha',  # some other role
         'perm_whitelist': [],  # a list of perm names that should be added 
         'perm_blacklist': [],  # a list of perm that should be removed
    }
}
```

**Comment by mistercrunch** [comment]
@georgeke here's another good ramp task if you want to pick this up

**Comment by alanmcruickshank** [comment]
@georgeke & @mistercrunch I don't know if it's an easy part to add, but
role inheritance would be really useful at some point too - and not just in
the config file but also in their live incarnations too.

As background, I have a base "viewer" user (very similar to the Gamma
user), and there are some datasources that I'd like to only give access to
for particular users (for arguments sake call them "finance"), but they
should otherwise have exactly the same rights as the "viewer" users. If the
"finance" use could inherit from "viewer" and only add the additional data
sources that would mean not maintaining two parallel roles with almost
identical privileges.

Thanks!

On Tue, 17 May 2016 at 17:47 Maxime Beauchemin <notifications@github.com>
wrote:

> @georgeke <https://github.com/georgeke> here's another good ramp task if
> you want to pick this up
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/airbnb/caravel/issues/479#issuecomment-219779884>
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825
