### ISSUE TITLE
Any Instruction on Deploying Superset on AWS Elastic beanstalk?

### ISSUE THREAD

**Issue by Him121** [apache/incubator-superset#4824]
Hi Can you please direct me on instruction if available to deploy Superset on AWS Elastic beanstalk? and also setup HTTPS.

Thanks,

**Comment by mistercrunch** [comment]
I know nothing about Beanstack, but maybe this helps:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-flask.html

If you get through hardships please share with the rest of the community.

**Comment by Him121** [comment]
Sure... planning to setup on next few weeks for demo.... Will share. Thanks.

**Comment by kirankumarpv** [comment]
Hi, 

I have tried setting it up on Elastic Beanstalk. Initially ELB is throwing many errors as many of the pre-requisite tools that are required for deploying superset are not available when ELB tries to deploy the application. So, in order to overcome that, I had to use prehooks feature for ELB to install pre-requisites before actually AWS tries to deploy the application. 

This is what i have setup in .ebextensions folders 

01_pre_deps.config
`packages:
  yum:
    gcc: []
    gcc-c++: []
    libffi-devel: []`

91_update_env.config
`files:
  "/opt/elasticbeanstalk/hooks/preinit/91_update_env.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      yum install gcc gcc-c++ libffi-devel python-devel python-pip python-wheel openssl-devel libsasl2-devel openldap-devel cyrus-sasl-devel.x86_64`

99_init_superset.config
`files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/99_init_superset.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      . /opt/python/run/venv/bin/activate
      fabmanager create-admin --app superset --username admin --password admin --firstname admin --lastname admin --email admin@gma.com
      superset db upgrade
      superset load_examples
      superset init
      gunicorn -w 4 -k gevent --timeout 120 -b  0.0.0.0:443 --limit-request-line 0 --limit-request-field_size 0 --statsd-host localhost:8088 superset:app wsgi & `

After doing the above, I was able to get the environment up and running but on AWS Beanstalk AWS automatically does a health check and deletes an instance if it finds the instance health is not right. 

For the ELB environment that's being setup for superset, AWS is continuously failing health checks and it's invoking EC2 instances replacement due to which i wasn't able to get a stable ELB env up and running. 

I need to find out why health checks are failing on AWS EC2 instances invoked by ELB and if that's resolved, then should be able to bring up stable env on ELB. 

Thanks

**Comment by mistercrunch** [comment]
Note that we now have a `install/` folder in the repo where you could you could add a `install/beanstack` folder and share a reference implementation if you think it makes sense to do that.

**Comment by frankhsu** [comment]
@kirankumarpv That seems pretty tough. If there isn't a reason for a more tailored installation, I have got it working fine via a multi-docker container deploy on elastic beanstalk. Using the official redis image and @amancevice 's https://hub.docker.com/r/amancevice/superset/ image. Your Dockerrun.aws.json would simply just be those two images with a superset_config.py volumed in. Just make sure the ELBs and SGs are all playing nice and talking.

**Comment by aboganas** [comment]
any updates on this?
