### ISSUE TITLE
Invalid '*' corrupting connection password

### ISSUE THREAD

**Issue by outerlook** [apache/incubator-superset#4826]
I was going to ask for help, but I discovered the cause, so I'm posting here with solution.

I was getting error while fetching my MySQL database's data, although I got "Seems ok" when testing sqla connection.
Like if it was getting corrupted after saving database's data.

My password contains * (asterisk) and after removing that I could execute things normally.
I don't know if I need to add some more detail.

**Comment by atharh** [comment]
This was a bug in sqlalchemy-utils: https://github.com/kvesteri/sqlalchemy-utils/issues/212

The database password is encrypted with a broken padding scheme which strips `*` characters. See [here](https://github.com/apache/incubator-superset/blob/370d8a2bbe9c57a869bd4fc9726402fddb3cdb54/superset/models/core.py#L561).

The fix is to upgrade sqlalchemy-utils and [use  PKCS5 padding with `EncryptedType`](http://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.encrypted.encrypted_type).
