### ISSUE TITLE
am unable to find stacked bars feature in the upgraded superset. I can't find chart options as it was before I am finding it difficult to use breakdowns.

### ISSUE THREAD

**Issue by neshkatrapati** [apache/incubator-superset#5168]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Wait I don't think bar charts have changed in a while. Maybe it's confusion over time series bar chart and distribution bar charts? Or did you upgrade from a very old version?

**Comment by neshkatrapati** [comment]
I dont think I have upgraded from a very old version. There might have been a three month gap at the most. But, I am unable to see the chart options menu and go for stacked bars.

**Comment by tingzhouu** [comment]
For anyone looking to create a stacked, time-series bar chart. Use a **Time-series Bar Chart**, and the chart will be stacked once **GROUP BY** has been set.

<img width="332" alt="Screenshot 2021-03-25 at 11 51 35 PM" src="https://user-images.githubusercontent.com/33824745/112502958-7d962e00-8dc5-11eb-962e-9f5696cc8d9f.png">

**Comment by oskarabc** [comment]
@tingzhouu Invoking a group by statement wouldn't work in this case I believe as it would just group and not show separate values for each value of a visual total. In my reading OP is after just manipulating visuals, rather than underlying data.

As it took me 20 minutes to find this first time around, here are steps and a screenshot: First pick the time-series bar chart from the Data menu (or tab) in the side bar under Visualisation Type. Then navigate to the Customize menu (or tab) and look for the "Stack Series" option nested under Chart Options.

![Screenshot 2022-07-30 at 13 29 03](https://user-images.githubusercontent.com/51824794/181909113-e8694f86-7169-4f96-ad8d-a36531bf6bca.png)

At the time of writing I'm using version 2.0.0.

**Comment by NicolasPA** [comment]
I also had issues finding this function in version 3.1.1, it's well hidden in Bar Chart > Customize > Chart Options > Stacked Style

Here's a solution for 3.1.1 using the provided example dataset `video_games_sales`:
![image](https://github.com/apache/superset/assets/22459427/98d5bf2f-29f0-4d71-bac0-177f4831dba1)
![image](https://github.com/apache/superset/assets/22459427/f02f6848-97d7-411b-b410-e630ad18de91)
