### ISSUE TITLE
Changed of Date to  epoch time in Table view - Superset - 0.25.6

### ISSUE THREAD

**Issue by rohanagg** [apache/incubator-superset#5182]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results
Expected result in 0.17.6 is : 
![image](https://user-images.githubusercontent.com/30650330/41275495-ac6b8076-6e3e-11e8-8098-c642e79f6179.png)

### Actual results
Actual result which I am getting in 0.25.6 is : 
![image](https://user-images.githubusercontent.com/30650330/41275520-cc665dba-6e3e-11e8-8f48-67fbc99b9a81.png)

### Steps to reproduce
Open the slice and select the table view.
In the group by select any column with date as datatype
select any metric against it.
Output is epoch time against the metric

**Comment by llozanoc** [comment]
I'm having the same problem with the timestamp types and Table views

This problem is reported in the issue #3027 for the "NOT GROUPED BY" colums, but in my case I'm selecting a timestamp value in the group by. 

Anyway without grouping by date the problem persists.

![image](https://user-images.githubusercontent.com/18721916/41424718-2342de3a-6fff-11e8-842f-26b62167d578.png)

However, with a *Distribution - Bar Chart* , the format of the date is correct

![image](https://user-images.githubusercontent.com/18721916/41424650-f737b2fc-6ffe-11e8-8def-2ab33588a513.png)

**Comment by amzhang** [comment]
+1

**Comment by csc5k** [comment]
+1

**Comment by rohanagg** [comment]
Issue still exists in Version 26.3.. Table view shows date in epoch format.. While it is solved in case of Pivot view

Table View - 
![image](https://user-images.githubusercontent.com/30650330/42925238-1c57eb62-8b4b-11e8-96e7-db5ff20b2aba.png)

Pivot View - 
![image](https://user-images.githubusercontent.com/30650330/42925282-416fd90a-8b4b-11e8-8378-a8c93b9c15ad.png)

Are we doing anything to cater such things in future versions. Our company runs on Superset but because of such issues it becomes hectic for business owner to get attached to Superset as a visualisation tool

**Comment by rohanagg** [comment]
Can someone help here. As it is becoming blocker for day to day activity and we are not able to superset to latest version

**Comment by awsiotdemo** [comment]
+1

**Comment by ngoclong19** [comment]
A temporary solution is casting the date to string. We create an additional dimension with this expression `TO_CHAR(date, 'yyyy/mm/dd')`.

**Comment by kakoni** [comment]
Still present in 0.29. It is caused by this commit
https://github.com/apache/incubator-superset/commit/0ec9cd4ad279c24b6d65fb825a319357958297fd

Basically datetime date field gets formatted by BaseViz.json_dumps that uses json_int_dttm_ser serializer which turns date into epoch.

@mistercrunch I guess that commit fixed non grouped options, but in turn broke grouped.
