### ISSUE TITLE
Add support for hosting superset DB in greenplum

### ISSUE THREAD

**Issue by gbates101** [apache/incubator-superset#5250]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
4b7a14de (building from source)

### Expected results
Running database migrations against a greenplum database creates all database objects successfully.

### Actual results
Some components of the current superset DB schema are incompatible with a greenplum database, particularly the DDL for creating tables.

### Steps to reproduce
In the below example, I ran `superset db upgrade` against a greenplum database, and recieved an error informing me that `Greenplum Database does not allow having both PRIMARY KEY and UNIQUE constraints`. The root issue here is that a primary key IS a unique constraint in greenplum, and only one unique constraint can exist on any given table. I have four options to rectify this, the first three requiring schema changes:
- Drop the primary key in favor of the unique constraint. 
    - This would still allow only 1 unique constraint per table.
- Drop the unique constraint altogether.
    - This would probably have unintended consequences.
- Add the column(s) with the unique constraint(s) to the PK instead.
    - This would lose the individual uniqueness of each column.
- Modify the sqlalchemy dialect for greenplum to ignore unique constraints if a PK is defined.
    - This will probably be the least invasive, but may still have unintended consequences.

Assuming I can take one of the options above without complication, I can think of two options for adding GP-specific migrations:
- Create a branch from the root migration in superset's migration repo, and start fresh for a GP installation.
    - This branch could be labeled as "greenplum" or something useful. I believe this would require users to specify which branch they want to migrate from when running `superset db upgrade`.
- Squash the existing migrations, and switch to the flask-multidb template.
    - This will require all consumers define a SQLALCHEMY_BINDS in their config, mapping an engine to a URL.

I believe adding support for GP will also require model changes for flask-appbuilder's security models. The `SecurityManager` will [create tables](https://github.com/dpgaspar/Flask-AppBuilder/blob/98b1be8b3390cd592dc20f215062e55d27e08eec/flask_appbuilder/security/sqla/manager.py#L75) from FAB's base model if the tables do not exist (this circumstance is how I reproduced the example below). It may be useful to define overrides for the FAB security models that do not have unique columns defined, though this seems like extra work that could be avoided with a greenplum dialect change.

All-in-all it seems feasible to add support for hosting superset in greenplum, but I don't yet have it all figured out. What do you think?

### Example
Ran migrations on an empty greenplum database with a database role that has full DDL access:
```bash
$ superset db upgrade
...
INFO:sqlalchemy.engine.base.Engine:{'name': 'ab_permission_id_seq'}
INFO:sqlalchemy.engine.base.Engine:
CREATE TABLE ab_permission (
        id INTEGER NOT NULL, 
        name VARCHAR(100) NOT NULL, 
        PRIMARY KEY (id), 
        UNIQUE (name)
)


INFO:sqlalchemy.engine.base.Engine:{}
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.ProgrammingError) Greenplum Database does not allow having both PRIMARY KEY and UNIQUE constraints
 [SQL: '\nCREATE TABLE ab_permission (\n\tid INTEGER NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by inviscid** [comment]
One consideration might be to make the primary key a combination of database + schema + table/view with the ID column only serving as a reference.  Since the ID column is auto incremented, it will always be unique without having to specify it directly.  This way the ID column can be indexed for performance reasons but not have a unique constraint applied.

**Comment by mistercrunch** [comment]
I don't think Greenplum is meant to be used for OLTP workloads. MPP databases are designed to take on vertical workloads.

**Comment by gbates101** [comment]
@mistercrunch Agreed. We have some internal requirements that make hosting superset in a greenplum database ideal, and were hoping we could develop a solution that won't require us to maintain a fork permanently while benefiting others that may find greenplum support useful.

**Comment by inviscid** [comment]
@mistercrunch totally agree that Greenplum is not an ideal OLTP style RDBMS.  OLTP encompasses a wide range of possibilities.  Superset isn't really doing traditional OLTP type activities, it is simply using the database as a relational database.  Some OLTP systems have heavy referential integrity while others built for speed (10k transactions/second) have only the most minimal checks.

Bottom line is that it really depends on use cases and where selecting a sub-optimal technical platform may improve the overall solution optimality.  The challenge with advocating a two database platform solution is complexity, cost, and people.  Since Superset's use of the database is not overly taxing, it seems like a good idea to allow it to support the widest set of databases possible to encourage adoption and remove barriers to economical use.

Since Greenplum can be supported through SQLAlchemy it seems like a worthy target database in the future.

**Comment by mistercrunch** [comment]
@inviscid I really don't think this is a good idea and doubt it will fly

On this thread Ivan Novick, Product Manager Pivotal Greenplum is pretty clear about it "pure OLTP: no, its not appropriate.":
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/pycQgX1lR04
