### ISSUE TITLE
[Metric Creator] For Druid datasources, not all aggregations work (only Count works)

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#5378]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
For druid datasources, the interactive metric creator in explore view 
needs to hide those aggregations that do not work. My understanding is that Druid requires these metrics to have post-aggregations set up.
We should hide the aggregations that don't work (short term)
Longer term, we should create these aggregations for Druid as well
<img width="347" alt="screen shot 2018-07-11 at 10 00 45 am" src="https://user-images.githubusercontent.com/33429480/42588129-c2c819a0-84f1-11e8-9a1f-5562505ea8df.png">

**Comment by srggrs** [comment]
this is because in the latest master version the Druid Metrics are not retieved, only the COUNT:

![image](https://user-images.githubusercontent.com/34258464/51952993-aabd4f00-248e-11e9-8ace-e408e2b96773.png)

Before when using the "refresh Druid Metadata" button, Superset retrieve the metrics from Druid and populate its backend with those
