### ISSUE TITLE
Can't add a table with same name as table existing in an other schema

### ISSUE THREAD

**Issue by CyrilLeMat** [apache/incubator-superset#5557]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
I have a Postgresql Database.
I have already added the table  'schema1.table_name'
I want to add the table 'schema2.table_name'

### Actual results
I can't add the table, I got the message "Integrity error, probably unique constraint" in the tablemodelview/list/ screen
![image](https://user-images.githubusercontent.com/7548748/43652225-df99f9f8-9744-11e8-9381-04dc9dcb8d88.png)

### Steps to reproduce
Adding a postgresql database
In postgresql, Creating 2 Schema & Adding 2 table with same names in the schemas
In superset, Adding the first table then the second one

**Comment by mistercrunch** [comment]
We've tried to fix this issue many times (grep for `unique` in the `migrations/` folder for evidence of this) and I think it's just impossible to remove constraints using alembic on some databases because of non-deterministic constraints names. I'd recommend to manually delete the constraint using DML against your database.
