### ISSUE TITLE
build docker image fail

### ISSUE THREAD

**Issue by ifcute** [apache/incubator-superset#6011]
Step 26/30 : RUN cd superset/assets && yarn --verbose
 ---> Running in 9f3d88d1e86f
ERROR: There are no scenarios; must have at least one.
The command '/bin/sh -c cd superset/assets && yarn --verbose' returned a non-zero code: 1

**Comment by victornoel** [comment]
@ifcute could you try this branch #5966 and see if it works as expected?

**Comment by songyixu** [comment]
Hi @victornoel,
I got the same error today with the newest code pulled.   So, seems the issue is still there.

Removing intermediate container a960c6b30d83
Step 23/27 : RUN cd superset/assets && yarn
 ---> Running in be23ca21021a
ERROR: There are no scenarios; must have at least one.

**Comment by victornoel** [comment]
@songyixu can you show me the command you run to build the image and have you modified the Dockerfile or any other file?
The error you are referring to is this one: https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365. This is very strange that happens inside docker.

**Comment by victornoel** [comment]
@ifcute if you are talking about the same problem that @songyixu is talking about, then I was proposing to test the content of the not-yet-merged PR #5966 which changes this documentation. So if you tried it, you need to follow the instructions available in it.

Furthermore, the error from yarn is because it is the wrong yarn binary that is used. Maybe you are relying on an old version of the image `python:3.6`? Try running `docker pull python:3.6` before building the superset image.
