### ISSUE TITLE
Specifying Date range for a chart

### ISSUE THREAD

**Issue by CyrusQlarion** [apache/incubator-superset#6070]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

I am trying to put a date range on a chart to show data only for the last 6 months (not including this month). For example, today's date is 10/10/2018, and I would like to see data from 4/1/2018 to 10/1/2018 (until end of 9/30/2018 and not including 10/1/2018). I figured out the Since part to put 
"one day after 7 months ago eom" but for the Until section, I don't know what I can put. Can you please assist me?
I tried adding "1st" to Until, but when I look at the query generated by Superset, I see the following:

WHERE start_date >= '2018-04-01 00:00:00'
  AND start_date <= '2018-10-01 00:00:00'
GROUP BY DATE_TRUNC('month', start_date) AT TIME ZONE 'UTC'
LIMIT 5000;

but I don't want to include '2018-10-01 00:00:00', meaning the expression should only be LESS THAN not LESS THAN OR EQUAL.

### Superset version
0.25.2

### Expected results
WHERE start_date >= '2018-04-01 00:00:00'
  AND start_date < '2018-10-01 00:00:00'
GROUP BY DATE_TRUNC('month', start_date) AT TIME ZONE 'UTC'
LIMIT 5000;

### Actual results
WHERE start_date >= '2018-04-01 00:00:00'
  AND start_date <= '2018-10-01 00:00:00'
GROUP BY DATE_TRUNC('month', start_date) AT TIME ZONE 'UTC'
LIMIT 5000;

### Steps to reproduce
I would like to figure out the correct value/expression for Until part the of the Time/date range to filter data until end of last month. I tried "1st" but that doesn't help me since it is including the first day of current month

**Comment by ecdavis** [comment]
Adding more info around this issue.

## Bar chart viz scoped to last day includes data from last two days

### Superset version
This SHA: https://github.com/lyft/incubator-superset/tree/50aca10b85b12191643e97341559bab382c0e584

### Expected results
A bar chart scoped to the last day using the time controls should only display data from the last day.

The query used for the chart should be:
```
SELECT column_name AS column_name,
       COUNT(*) AS count
FROM public.table_name
WHERE snapshot_date > '2018-11-08 00:00:00'
  AND snapshot_date <= '2018-11-09 00:00:00'
GROUP BY column_name
ORDER BY count DESC
LIMIT 50000;
```

### Actual results
A bar chart scoped to the last day using the time controls displays data from the last two days.

The query used for the chart is:
```
SELECT column_name AS column_name,
       COUNT(*) AS count
FROM public.table_name
WHERE snapshot_date >= '2018-11-08 00:00:00'
  AND snapshot_date <= '2018-11-09 00:00:00'
GROUP BY column_name
ORDER BY count DESC
LIMIT 50000;
```

### Steps to reproduce
We use a PostgreSQL datasource. Our table has a column "snapshot_date" which has a type of DATE. We have multiple rows with the same "snapshot_date" value and want to create a bar chart which counts the number of rows in the last day.

This problem is exacerbated when using the DATE column type, because date comparisons ignore times. `'2018-11-08' >= '2018-11-08 hh:mm:ss'` will always evaluate to true, regardless of the value of hh, mm, or ss because the date parts are equal. Similarly, `'2018-11-09' <= '2018-11-09 hh:mm:ss'` will always evaluate to true, regardless of the value of hh, mm, or ss because the date on the left is less than the date on the right. This is also a problem when using the TIMESTAMP column type, however, because the time window superset is currently producing is 86401 seconds (1 day + 1 second), rather than 86400 seconds (1 day).

### Screenshots
Viz type and time controls on chart.

![screen shot 2018-11-09 at 10 37 54 am](https://user-images.githubusercontent.com/730735/48281464-8ad83b00-e40b-11e8-970b-8ec264113718.png)

Actual behavior:

![screen shot 2018-11-09 at 10 55 42 am](https://user-images.githubusercontent.com/730735/48282317-384c4e00-e40e-11e8-85d5-f4f135f10197.png)

Expected behavior:

![screen shot 2018-11-09 at 10 56 56 am](https://user-images.githubusercontent.com/730735/48282341-47330080-e40e-11e8-82a0-3752c148b7f0.png)

**Comment by thenooz** [comment]
Try "last month eom and 23:59:59". It works for me. Superset version: 0.29.0rc7
