### ISSUE TITLE
Can't turn off download/export permission?

### ISSUE THREAD

**Issue by dizzydes** [apache/incubator-superset#6116]
Hi,

Referencing #6110 I turned off 'can csv on Superset' for a gamma user then logged in as them and they still successfully downloaded a csv of a table's results.

Adding data source access to their profile wouldn't have caused any issues, would it?

<img width="556" alt="screen shot 2018-10-16 at 09 56 03" src="https://user-images.githubusercontent.com/10514807/47005386-8b8ef180-d12b-11e8-8b0e-3c5eb238fa2c.png">

Happy to provide a login if its faster to see.

Thanks

**Comment by dizzydes** [comment]
There is also a 'can csv' under menu permissions but I don't see a way to turn this off; I assume its related to 'can csv on superset'
<img width="761" alt="screen shot 2018-10-16 at 10 42 17" src="https://user-images.githubusercontent.com/10514807/47007500-44efc600-d130-11e8-9c4a-2c8722d34ea9.png">

**Comment by dizzydes** [comment]
Yes i edited the gamma role by removing this permission. The gamma role was
attached to the user i tested.

**Comment by emacip** [comment]
@mistercrunch I try removing the permission "can csv on Superset" and its not working, in the other hand if I remove "can explore on Superset" the explore link disappears. 
@dizzydes how you fix the problem?

Thanks

**Comment by jeremyhiggs** [comment]
I noticed this too. I removed "can csv on Superset" from the Gamma role, and via the Explore tab the CSV could still be downloaded.

**Comment by sabinegthomsen** [comment]
It doesn't work for me either.

**Comment by FrankScarlet** [comment]
> I noticed this too. I removed "can csv on Superset" from the Gamma role, and via the chart/slice page the CSV could still be downloaded.

Do you find a way to solve it ? I met a similar situation. 
I removed 'can csv on Superset' from the Gamma role so that they can not export to csv from sql_lab page.
But I found that the user can still type 'select * from tb' in sql_lab, explore it in chart, and finally export csv/json from the chart

![image](https://user-images.githubusercontent.com/25702099/94092179-a3f60380-fe4c-11ea-8a12-f87b74988eaf.png)
 

I will provide detailed infomation on the permission of my custom role if needed. (Generally it is a combination of Gamma, sql_lab, Public)

**Comment by opus-42** [comment]
Hello, @FrankScarlet : hope it's not too late. I encounter a similar issue and found the solution in reading the source code.

The linked permissions for this button is "can_download on SliceModelView". The reason is the following:
- This button is linked to a can_download in the Front Code.
- The corresponding permissions for the backend is "can_download on SliceModelView"

Not sure what is the rationale behind it though, it may be some legacy thing and could be a good idea to clarify it. 
Hope it helps
