### ISSUE TITLE
413 Request Entity Too Large error with csv file

### ISSUE THREAD

**Issue by johnfelipe** [apache/incubator-superset#6456]
[socialcsv.zip](https://github.com/apache/incubator-superset/files/2625590/socialcsv.zip)

I need put that table in source
But when put SAVE this is error:

![snag-0021](https://user-images.githubusercontent.com/428820/49163750-ce7fdf80-f2fb-11e8-9437-cd837b0af1c9.png)

How can solved?

**Comment by mistercrunch** [comment]
Looks to me like a nginx configuration thing.

**Comment by johnfelipe** [comment]
i do this:
https://stackoverflow.com/questions/26608606/413-request-entity-too-large

but now show this error:

![snag-0032](https://user-images.githubusercontent.com/428820/49202514-daf34f00-f372-11e8-930c-cd02427020ee.png)

**Comment by asmaier** [comment]
Note: If you are running Superset on a kubernetes cluster you might run into that issue, because "the ingress nginx has a proxy-body-size default value set to "1m"." So one cannot upload a file bigger than 1m with the default configuration of the ingress/reverse proxy/nginx controller:

https://github.com/kubernetes/ingress-nginx/issues/4262
