### ISSUE TITLE
Adding code to transformProps that changes data gets rendered each chart change

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6466]
This is more of a code quality suggestion for the future / FYI as opposed to a bug that's currently affecting users. I mentioned this in this [PR](https://github.com/apache/incubator-superset/pull/6465), `transformProps` gets run every time the chart or chart controls changes. It seems like `transformProps` might not be a great place to alter the data because it gets executed before the user has clicked run, so it could change the chart automatically when a control changes in ways that we might not expect.

As an example, in big number when you clear a metric, instead of showing the overlay, we'll show NaN before the user has clicked RUN because the data gets processed in transformProps so data returned to the chart will be null until the user selects a new metric. 

I talked with @kristw about this in person, just wanted to leave this here to give others an FYI of what we found out. Not sure who to tag.

cc: @conglei @kristw 

### Superset version
master

**Comment by mistercrunch** [comment]
So we used to have a handle on the `payload.formData` AND the current `formData`. The difference is subtle but important. I'm not sure if it's a timing of "what should run when" as discussed here, or just having a clear handle on both things. 

@betodealmeida and I have discussed thing in the context of the `granularity` control, where in some cases were interested in `payload.formData.granularity`, think "what was the granularity on the latest query".

This is common to all form controls that affect both the query and that are used in the javascript.

**Comment by conglei** [comment]
@michellethomas @michellethomas @kristw 

FYI I'm now working on this issue now.  I feel like this issue should be handled in a higher level, so rendering won't be triggered if the change is not for instant change.  Even if we `payload.form_data`, the chart will be rendered again, which will affect the performance a lot in explore view.

**Comment by mistercrunch** [comment]
I agree about not re-rendering when not required, though the bug would still happen if changing metrics, and then changing some `renderTrigger: true` control.

**Comment by conglei** [comment]
One downside for the proposed solution is that, users cannot change multiple controls and run the query at once.

**Comment by mistercrunch** [comment]
To me it's pretty clear that sometimes we need the `formData` of the payload, that is the relevant state that we're trying to represent. When that's the case (and that's not super common), I think it's perfectly fine to hook it up in the `transformProps`.

**Comment by mistercrunch** [comment]
For metrics specifically, many visualizations show metrics labels in legends and tooltips, and in all cases the metric that matters is the one at payload time. That works when the metric label is part of `payload.data`. We may want to do an all-around sweap of each visualization and make sure things are hooked up properly, that no other viz make the same mistake as `BigNumber`.

For example, NVD3 line chart metrics are in sync because we bake them in the `payload.data` as "Series Labels". The fix for `BigNumber` could have been to add metrics information to the `payload.data` by reshaping it somehow, but the metric info is there in `payload.formData` so I used it in my fix.

Anyhow to me it's not a timing issue as much as pointing to references that in-time may be be out of sync. The fix I push makes sure that in-time, the references should always be consistent.
