### ISSUE TITLE
Fail to install on ubuntu 16.04

### ISSUE THREAD

**Issue by richiesgr** [apache/incubator-superset#6474]
Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Master branch Git

### Expected results
Build using docker scripts must build a version running

### Actual results
Fail to compile with this message 

void _ssl_thread_locking_function(int mode, int n, const char *file,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1

### Steps to reproduce
Follow exact procedure described [Here](https://superset.incubator.apache.org/installation.html#start-with-docker)

### Solution 
cryptography=1.9 in requirements.txt doesn't compile on ubuntu 16+ need to switch to version 2.1.1

**Comment by villebro** [comment]
`cryptography==1.9` is quite old, and is incompatible with some SQLA connectors, so should ideally be updated as `setup.py` doesn't restrict the version. I tried running `pip-compile -U --output-file requirements.txt setup.py` to see what versions a fresh install would pull in, and noticed that the `botocore` versions in setup.py seem to be problematic:

```
Could not find a version that matches botocore<1.13.0,<1.8.0,>=1.12.57,>=1.7.0
```

Seems like there was an issue #5175 that was fixed by restricting the version that should be revisited..
