### ISSUE TITLE
How to customize the theme

### ISSUE THREAD

**Issue by subbiaht** [apache/incubator-superset#6558]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
You essentially need to fork and make your own builds.

This is a good place to start: 
https://github.com/apache/incubator-superset/blob/master/superset/assets/stylesheets/less/cosmo/variables.less

We serve a display page for the theme you can use while you tweak it: `/superset/theme/`

**Comment by gbrian** [comment]
@mistercrunch does it make sense to have global CSSTemplates? 
We can flag a CSS template as global and load it at "superset/basic.html" so it applies always. It allows basic theming without having to maintain a separate repository. 

![image](https://user-images.githubusercontent.com/767180/58939407-737de800-8777-11e9-9c69-3deecefecbae.png)

Then at the end of the `head` section:

```
{% for entry in global_css %}
        <style>
          {{ entry }}
        </style>
    {% endfor %}

```

**Comment by mistercrunch** [comment]
Feels like it shouldn't live in the database, it would mean an extra query to the DB all the time. The best here is probably to make your own build in your own fork. To avoid conflict you copy/paste the folder with the theme and alter the code to import that instead of the current theme.

Otherwise, and assuming you don't want to alter the Python package, maybe a new config key `EXTRA_CSS_FILES = []` (would load on top of current theme), or `CUSTOM_BOOTSTRAP_THEME = 'https://mydomain.com/mytheme.css'` which would  prevent loading the current theme from loading and load yours?
