### ISSUE TITLE
[Design Proposal] Improve SQL Lab Editor Resizer

### ISSUE THREAD

**Issue by thinmatt** [apache/incubator-superset#6565]
The current UI of the SQL Resizer is not as discoverable as it could be. Want to update the UI to use a more standard convention than he single 2px rule. In addition, the location of the resizer between the SQL Toolbar actions and the results tabs does not communicate to users that sql editor pane is resizeable. I've seen users struggle with this as I've observed them use SQL lab.

My recommendation would be to 
* (1) **add an additional UI element to the resizer component** to hint that the resizer can be "grabbed." A single line isn't often enough to communicate that concept in a UI (especially with borders on so many elements in the SQL Lab layout).
* (2) **assess the location of the resizer element or the visual design of the SQL Toolbar actions**. From a UI standpoint, it would be more intuitive for the resizer component to be above the SQL toolbar _or_ for the SQL toolbar to visually match up with the editor pane -- that way the resizer is the true visual edge of the editor pane

I have attached a few different UI mocks to represent the ideas:

### Additional UI for resizer with resizer at the visual botton of the sql editor pane
![sql lab pull - 3 1](https://user-images.githubusercontent.com/527868/50366987-e3821400-0531-11e9-9583-942f8db60f39.png)

### Making the SQL toolbar visually a part of the editor
![screen shot 2018-12-21 at 2 11 55 pm](https://user-images.githubusercontent.com/527868/50365681-83d43a80-052a-11e9-864c-f6d724f0763c.png)

### Both concepts combined (recommended approach)
![sql lab pull - 3 3](https://user-images.githubusercontent.com/527868/50366991-eb41b880-0531-11e9-9f4f-4995877921db.png)

If it's decided that we want to make the SQL toolbar visually appear as a part of the SQL editor pane, we will need to make a small adjustment to how Ace Editor styles the gutters (likely a simple override in the styles). Ace currently darkens the gutters, which in and of itself isn't an issue, but when you get to more than 10 lines of code, the gutter widens slightly. My recommendation would be to make the gutter the same color as the main editor pane, then add a border-right to designate where the right most part of the gutter is.

**Comment by kristw** [comment]
For the "Making the SQL toolbar visually a part of the editor" (2nd mock). How would it look if the SQL code has many lines and exceed the editor height? Does the code still show up behind the button? If there is a hard-end above the buttons, this seems a bit odd without border or some kind of indicator.

**Comment by xtinec** [comment]
I like @dorq 's proposal. The color difference between the light and dark grey should serve as a natural divide between code and the button area (i.e. code in the light grey area only). When the scorbar comes up, it would only scroll the code area.
 
I'm not sure where we want to left-align the 'Run Query' button. It looks a bit odd somehow to me to have it aligned "into the gutter" (now that the button area is the same grey, the left end of it looks like an extension of the gutter to me). 

I was thinking perhaps we could align it to the right side of the gutter. As @thinmatt pointed out, the gutter of the ace editor (code area) resizes based on the digits of the line number so in order to align the buttons to the right side of the gutter, we would need to reposition the buttons as the code area grows, which is silly. One possible way around it is to push all the buttons to the right. Perhaps?

**Comment by dorq** [comment]
I like the idea of pushing all the buttons to the right.  A couple of questions following up on that...

- Are the "parameters" button and time functionally different than the other buttons?  Would we want to keep them in a separate group from the other buttons?
- Would we want to reverse the order of the buttons so that the default "Run Query" is at the far right?

cc @vylc

**Comment by dorq** [comment]
Here's what the buttons look like indented to the right side of the gutter (even though we won't do exactly this), in case it's helpful:
![sql lab pull - indent](https://user-images.githubusercontent.com/2992086/50669245-e3920300-0f78-11e9-8d84-f9e7c2da46d4.png)

**Comment by dorq** [comment]
We could try a subtle top border to the buttons container:
![image](https://user-images.githubusercontent.com/2992086/50669354-8cd8f900-0f79-11e9-8ef7-d9f0bd01165d.png)

**Comment by dorq** [comment]
Thanks @mistercrunch!  I agree that we should be careful about the lag while dragging; thanks for pointing that out.  I do still think we want to add a visible handle and improve the grouping of the buttons with the query text area, to make this even more discoverable and intuitive.

Would love to hear your and everyone's thoughts on https://github.com/apache/incubator-superset/issues/6565#issuecomment-451327291

**Comment by vylc** [comment]
re: button organization and placement - we should probably table that right now since there will be even more with lightweight pipeline functionality. Ideally (not in any particular order):
Group 1 - Execute: Run query, Run query & create table
Group 2 - Do something with SQL: Save query, share query
Group 3 - Advanced SQL Editing: Parameterize query, possible UDF stuff
Group 4 - Advanced Execute: Backfill, Schedule, Make Dependent

I think we tackle in this order:
(1) Add grip bar/handle to existing separator w/out touching buttons (image)
(2) Figure out where we want to place buttons, whether or not that's in the SQL editor, an extended part of the gray area from the editor, etc.
(3) Button re-org
<img width="1109" alt="screen shot 2019-01-04 at 10 33 16 am" src="https://user-images.githubusercontent.com/33429480/50704537-92335380-100c-11e9-8432-42cd5c43948d.png">

**Comment by mistercrunch** [comment]
Related: https://github.com/apache/incubator-superset/pull/6593

**Comment by mistercrunch** [comment]
Fixed, props to @xtinec!
