### ISSUE TITLE
Sample drilldown...but uses highcharts :/

### ISSUE THREAD

**Issue by pavitranrambo** [apache/incubator-superset#6774]
**Multiple chart drilldown**

![multi_chart_drilldown](https://user-images.githubusercontent.com/45376692/51878540-02828a00-23ab-11e9-992e-ec4d242ad3d0.gif)

**Single chart drilldowns**

![single_chart_drilldown_column](https://user-images.githubusercontent.com/45376692/51878566-16c68700-23ab-11e9-99cb-36d98d54df13.gif)

![single_chart_drilldown_pie](https://user-images.githubusercontent.com/45376692/51878574-1af2a480-23ab-11e9-8a54-eebc049b6250.gif)

**Comment by XuanmoFeng** [comment]
Why not use echarts? Why not use D3?
Highcharts is not free

**Comment by pinky884** [comment]
@pavitranrambo Is this available in superset already? I have a requirement to create drill down graph using superset but I am not seeing HighColumn Chart in the visualization type. Is this change not available in superset already?

**Comment by zpanderson** [comment]
+1 on this.  This is one feature that I'm missing to move from PowerBI to Superset.

**Comment by xwydq** [comment]
@pavitranrambo Is this available demo for your display? that is great!

**Comment by nisanth456** [comment]
please mention github code change for drill down

**Comment by GunaSekhar1420** [comment]
Is this feature available in superset in the latest version?? If not, It would be great to know how to implement it.

**Comment by maltoze** [comment]
Cool

**Comment by fzhan** [comment]
How can we create drill down charts like you have presented @pavitranrambo

**Comment by junlincc** [comment]
@pavitranrambo hey! This is super cool and we would like to bring it into superset but with Ecahrts. If you are interested in contributing or collaborating. please let me know! 🙏

**Comment by mistercrunch** [comment]
Do you refetch from the database or bring the drilldown data upfront? How do you know which dimension to drill into? What if there are multiple hierarchies?

**Comment by mistercrunch** [comment]
My take on "drill"-type interactions (drill down, drill through, drill across) is that we'll need a context-menu (or similar) since it's impossible to guess what the user expects or wants. Maybe there's a guessed interaction on a double-click.

Also I prefer a drill-across-first approach, since drill down requires upfront hierarchy semantics. Drill across allows to filter-and-pivot to any other dimension, which offers much more possibilities than the predefined hierarchies. 

Also note that alternate hierarchies (multiple paths to drill down into, state->zipcode or state->city) are a real thing and we need to think about what we do when they exist. We also need to think about where and how these hierarchy semantics are defined, most likely in the dataset editor.

**Comment by graceguo-supercat** [comment]
Superset started to use eChart library.

**Comment by micaimanong1** [comment]
> @pavitranrambo hey! This is super cool and we would like to bring it into superset but with Ecahrts. If you are interested in contributing or collaborating. please let me know! 🙏

Hello, is the code of this feature merged into master? Will the community develop the drill? How long will it be released?thanks.
