### ISSUE TITLE
There was an issue fetching the favorite status of this dashboard

### ISSUE THREAD

**Issue by AndreNalevaiko** [apache/incubator-superset#6824]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc7

### Expected results
Nenhum notificação de problemas

### Actual results
A notification with the following message

> There was an issue fetching the favorite status of this dashboard.

> Notification
![image](https://user-images.githubusercontent.com/30118955/52370286-a3231a80-2a39-11e9-9e45-ef72fa0333e0.png)
> Log javascript
![image](https://user-images.githubusercontent.com/30118955/52370301-aa4a2880-2a39-11e9-9f01-2026e71fefaf.png)

### Steps to reproduce
Open a dashborad

**Comment by Neuliaus** [comment]
we are having the same problem really weirdly, we thought it was because the CORS was disable on Superset Config, but after we enable it and re-deploy we still have the same problem. 

Because we are resolving other issues with removing the SQLite and replacing it with PSSQL on RDS , I dont know if they may be related or adding to it , or none of them . 

But maybe you should try enable the CORS in superset config and maybe it works for you

**Comment by graceguo-supercat** [comment]
modern browser doesn't like to mix https ajax in a http requested page. Can you set page dash.gorillascode.com with https request?

**Comment by mistercrunch** [comment]
Try setting `ENABLE_PROXY_FIX = True` in your `superset_config.py`, find more context here https://github.com/apache/incubator-superset/pull/1150

**Comment by ngritsuk** [comment]
We are using nginx as a reverse proxy for superset and faced with this issue. Superset is running in docker container and nginx is on the host system.
Following lines in nginx config solved this issue for us:

```
map $http_upgrade $connection_upgrade {
  default       "upgrade";
  ""            "";
}
 server {
 server_name superset.example.org
 listen 443 ssl;
 location /  {        
           proxy_set_header   Connection $connection_upgrade;
           proxy_set_header   Upgrade $http_upgrade;
           proxy_set_header   Host $host;
           proxy_set_header   X-Real-IP $remote_addr;
           proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto $scheme;
   }
}
...
```

**Comment by arthurpduarte** [comment]
There is a quick fix to this; the front-end is calling the wrong API and getting redirected with the wrong protocol if you are using HTTPS. The fix is adding a trailing '/' to the call. I created a PR for it, but I am no allowed to push the branch

**Comment by arthurpduarte** [comment]
> There is a quick fix to this; the front-end is calling the wrong API and getting redirected with the wrong protocol if you are using HTTPS. The fix is adding a trailing '/' to the call. I created a PR for it, but I am not allowed to push the branch

Reading up on how to submit a fix :)

**Comment by dequn** [comment]
set ENV `FORWARDED_ALLOW_IPS=*`  when starting gunicorn will solve it.
This issue is caused by lacking of trailing slash of `favorite_status` endpoint, and flask will append "/" and respond a redirection. But if flask can not detect it's under `https` scheme, you will get a `http` scheme location, then caused the error.
