### ISSUE TITLE
dataframe.py

### ISSUE THREAD

**Issue by fengshenme** [apache/incubator-superset#7025]
from pandas.core.common import _maybe_box_datetimelike
ImportError: cannot import name '_maybe_box_datetimelike'

dataframe.py  Changed to
14 .from pandas.core.common import maybe_box_datetimelike
94. data = [dict((k, maybe_box_datetimelike(v))

**Comment by MarcusSorealheis** [comment]
You may be seeing this `ImportError` because you are on `pandas  24.0.0`. The legacy datetime API is removed and replaced with another. I and a few others are investigating that issue atm. But for now, check to ensure you are on the correct version of `pandas`.

What's the output of:

`pandas --version`?

**Comment by MarcusSorealheis** [comment]
[here it is in the code](https://github.com/apache/incubator-superset/blob/d308c842f9fa3ffa4a1887e43a0757f24edf6cf5/setup.py#L91)

**Comment by MarcusSorealheis** [comment]
Run `pip install pandas==0.23.1` and try again.

**Comment by SamuelMarks** [comment]
@MarcusSorealheis What worked for me is `pip install pandas=0.23.4`
