### ISSUE TITLE
Question: Database and API validation Input 

### ISSUE THREAD

**Issue by MagicGary** [apache/incubator-superset#7043]
**This is not  feature/bug related**

Hi, 

I was wondering how superset does validation on data input on backend using Flask App Builder? Besides handling validation on the frontend, does it also handle validation on backend? 

much appreciated

**Comment by mistercrunch** [comment]
"Validation" in what context? In the broad sense of the term it's very endpoint-specific...

**Comment by MagicGary** [comment]
By validation I meant, 

For example: a column named Email of table User has type of string in DB. And the front-end will uses regex or etc. to make sure and validate that the user doesn't enter anything other than a valid email address.  

And my question was does this validation process also being applied somewhere on the backend to make sure if the API's POST Request's argument is any string rather than a valid email address, the endpoint will not allow this to be saved into Database? 

thanks

**Comment by mistercrunch** [comment]
I don't think we do validation on email addresses specifically, but if we wanted to we could.

One way to do this in FAB is by doing assertions on the ModelView's `pre_add` and `pre_update` methods and raise as needed.

Otherwise out-of-the-box there's some type checking on certain types, and that happens somewhere in FAB when we use the CRUD or REST that FAB exposes. Superset itself exposes many endpoints and they should be doing the needed validation, but not sure how rigorous it is.

Generally, and now that we deprecated support for python2, we're looking to introduce type annotations on the backend https://github.com/apache/incubator-superset/pull/7053, and generally there's a move towards more TypeScript in the frontend.

There's clearly a need for more rigor around type checking and validation throughout Superset, contributions that go in that direction are appreciated!

**Comment by MagicGary** [comment]
awesome! and thanks for this thorough explanation. 
We are building a project using FAB and Vue and wanting to use some good open source projects like SuperSet as the coding guideline. your answer makes great sense and much much appreciated!
