### ISSUE TITLE
[HELP!] Please close issues & PRs.

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#7160]
Thank you for all your contributions.

To keep the project maintainable, please help the community by 

- 🚮closing your issues that has been resolved, are no longer relevant or is duplicated.
https://github.com/apache/incubator-superset/issues

- 🚮closing your PRs that you no longer intend to merge or the code is not relevant any more. If the problem in the PRs still persists, please create an issue instead. 
https://github.com/apache/incubator-superset/pulls

Everyone closing 1-2 PRs/issues can really make a difference.

🗑️✨

**Comment by kristw** [comment]
Just created this one so I can pin it to the top.

**Comment by shankardevy** [comment]
@kristw what's your take on keeping general questions on the issue queue?   For eg., https://github.com/apache/incubator-superset/issues/7182

I'd love to help with the issue clean up but wanted to know if we can close any general question related to superset by providing a stock reply pointing to discuss the questions?

**Comment by kakoni** [comment]
@kristw Suggestion;
Superset github is filled with user questions. I believe this issue tracker should be only used for bug reports, feature requests and pull requests.

So perhaps there should be separate discussion forum for these questions? (=and where they would be kindly redirected to..)

**Comment by kristw** [comment]
@mistercrunch Should we divert questions to stackoverflow or sth like that?

**Comment by kakoni** [comment]
@kristw @mistercrunch Or setup forum like discourse https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/ ?

**Comment by mrshu** [comment]
Although there is a bandwidth limit of 50k monthly page views, I believe @kakoni's suggestion may be a bit better than StackOverflow.

**Comment by mistercrunch** [comment]
Stackoverflow's SEO is great. Wait is there a 50k limit!?

I wonder what the ASF would recommend. Please don't tell me the mailing list :(

**Comment by mrshu** [comment]
> Stackoverflow's SEO is great. Wait is there a 50k limit!?

@mistercrunch Sorry, I must have totally confused you. There is a 50k monthly page views limit for "free hosted" Discourse @kakoni mentioned above. As far as I know Stackoverflow does not have any limit at all.

**Comment by kakoni** [comment]
> I wonder what the ASF would recommend. 
@mistercrunch I believe for project core development its the mailing lists but for community/questions related bit unclear. For instance popular spark project main community channel is SO (https://spark.apache.org/community.html)

**Comment by hajdbo** [comment]
> Stackoverflow's SEO is great. 

And the superset and apache-superset tags already list about 300 questions: 
https://stackoverflow.com/questions/tagged/apache-superset
https://stackoverflow.com/questions/tagged/superset

**Comment by muraiki** [comment]
I agree that GitHub issues should not be used for user questions. But personally, I've commented in a few question issues because I couldn't find anywhere to get an answer, particularly regarding questions of great importance to adoption, such as what release candidate to use and the overall status / direction of the project. Furthermore, I commented on a PR that patched a vulnerability stemming from a dependency and still haven't gotten any detail on what the actual vulnerability is, and don't know if the various upgrades required (across release candidates) to merge the changes into my production instance will break my install. The difficulty in getting answers I think causes people to come here for lack of other options, so making a clear statement on where to go for support would be a big help. Sadly, this has led me to have to qualify every instance of my recommendation of this awesome project with negative caveats.

There's some activity on the Slack instance, but from what I've seen and experienced many questions go unanswered. I don't think that it's a good place to handle support, especially since the history limit will cause answers to be lost, resulting in spam as the same questions are asked repeatedly. It's also proprietary and requires signing up just to search.

While Stack Overflow is also proprietary, it does have excellent SEO that makes it easy for people to find answers to existing questions, as it's designed to produce long term support resources. It also doesn't require signing up to view answers (unlike if Slack was the preferred option).

A mailing list is the most open solution, but they tend to devolve into chaos.

Ultimately, an official avenue for support combined with a clear way to understand project status would hopefully reduce the incidence of general questions that have filled up GitHub issues.

I also suggest enabling the GitHub wiki for this project, if only to be a place to collect the top FAQs and perhaps to relay news. This can be edited more easily than constantly committing new README files.

Thank you all for your hard work on this project!

**Comment by hajdbo** [comment]
I suggest using a bot to automate closing the 900+ issues backlog.
The issues tagged with "question" could be immediately closed with a comment like "We keep GitHub issues for bugs, please ask questions on StackOverflow".
(+1 for enabling wiki)

**Comment by kristw** [comment]
@hajdbo I think several people agree that the bots will be great addition to the repo, not just for issues but there are several things bot can help. The difficulty is we need to open tickets to ASF admin to make the changes. It is a bit hard to experiment which bots work without admin access. Do you have any bots in mind that could be from other projects that you have experience with?

**Comment by kakoni** [comment]
@kristw When it comes to bots, probot (https://probot.github.io/). 
Look at https://probot.github.io/apps/stale/

**Comment by mistercrunch** [comment]
I ❤️  the idea of auto-labeling bots:
https://github.com/probot/autolabeler

Should be able to detect db migrations for instance, or classify backend/frontend, anything related to a file path regex works.

**Comment by kristw** [comment]
@kakoni I use multiple bots from probot in other repos.
* stale
* commitlint
* delete branch after merge
* label PR size by amount of change

Never use bot that can do more complex triaging or closing issues so would welcome recommendations here.

As I mentioned above about operating without admin rights, we better compile a list of specific bots that known to work before opening ASF ticket to add bots. Because if we add something that cause problems it may take time to remove.

**Comment by kristw** [comment]
I created an ASF ticket for a start. 
https://issues.apache.org/jira/browse/INFRA-18171

**Comment by kristw** [comment]
The bots above have been added. Requesting more bots to be added.
https://issues.apache.org/jira/browse/INFRA-18241
