### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by brylie** [apache/incubator-superset#7414]
There are several missing release tags since 0.28.0. It seems that rc versions are getting tagged, but stable release tags are missing. This makes it difficult to ascertain the frequency of stable releases.

**Comment by oliviermichaelis** [comment]
I think there are no stable releases yet due to licensing issues with Apache. See #6785 for further information.

**Comment by brylie** [comment]
Cool. However that shakes out, and however 'stable' is defined, there are still several missing point releases. E.g. 0.29, 0.30, 0.31 all have RC versions but no actual release. It seems odd to bump the release number without tagging a release.

**Comment by oliviermichaelis** [comment]
Is the issue still relevant? In case it's not, please consider closing it. Thanks :)

**Comment by brylie** [comment]
I I now understant more about the underlying reasons for the missing tags.


 believe this issue is a broader topic than #6785, and should remain open until the release tags are added.

**Comment by mistercrunch** [comment]
The ASF told us to not push non-ASF releases to Pypi or as Github tags until we sort out the ASF-compliant release process. I've been working on a release but work is still ongoing. There's a thread or 2 on the dev@ mailing list to follow.

Major work was to sort out licenses and move all 3rd party code out of the source release / Github repo.

**Comment by Webysther** [comment]
@mistercrunch exists any ETA for ASF-compliant release process?

**Comment by brylie** [comment]
Ping. This is a maintenance task that should not fall through the cracks.

**Comment by ericandrewmeadows** [comment]
@brylie - from my use, v0.33.0rc1 is stable; v0.34.0rc1 is not - I just wanted to give you some insight.

**Comment by mistercrunch** [comment]
@ericandrewmeadows the RC is getting voted on at this moment as the ASF mailing list, commenting on the voting thread would be more helpful. Also opening bugs with a `0.34` label would help us stabilize the release branch.

**Comment by mistercrunch** [comment]
The reason there's been no releases (and therefore no release tags other than RCs) is related to the complexity of the process imposed by the ASF along with the lack of volunteers to do the work to comply. It mainly consisted of sorting out and cleaning up licenses in our dep tree, as well as automating the process and preventing regression.  Also, well the release process is a bit clunky and hard to automate, especially the email crafting and voting part... Some of the steps have been recently documented here: https://github.com/apache/incubator-superset/tree/master/RELEASING

We were told pretty clearly by ASF folks to **not** release to pypi or any other methods that don't align with the ASF process. Which is reasonable: if we want to be an ASF project, we should comply to the rules of the ASF. While the community and meritocracy in the project has been vocal about being/staying part of the ASF, people haven't been jumping to offer to work in that direction.

It turns out that crafting a clean-licensed ASF-stamped release is not easy, and it's not super sexy work, so that's why it's taking time.

Luckily the project is super healthy in all metrics other than releases, and well I just kicked off a vote on general@incubator, so watch for the mailing list for a release, hopefully soon.

**Comment by brylie** [comment]
> Perhaps we could create a program to offset Whim users' carbon footprint, e.g. by contributing to sustainability projects via a registered charity. That way we could send a message that we are working to make transportation carbon neutral. 

I hope that doesn't preclude Superset from releasing an official Docker image, as that has turned out to be the biggest blocker for our company to even evaluate Superset against other projects like Tableau Server, Redash, Metabase, and Grafana.
