### ISSUE TITLE
Filter Box cannot be used only with time range, shows error

### ISSUE THREAD

**Issue by bipinsoniguavus** [apache/incubator-superset#7458]
When filter box is open in explore mode, then there is an error coming in the right hand side view. Then, add one more filters from select dropdown, the error will get vanished. 

### Expected results

When filter box is open in explore mode, then there should be no error and time range filters can be added by default without any other mandate filters

### Actual results

When filter box is open in explore mode, then there is an error coming in the right hand side view. Adding one more filters from select dropdown, will remove the error

#### Screenshots

![FilterBoxBug](https://user-images.githubusercontent.com/18305698/57205730-2ecb2980-6fde-11e9-81be-5988b997616a.gif)

#### How to reproduce the bug

1. Go to Charts and Add a new Chart
2. Choose a datasource and Choose a viz type as `FilterBox`
3. Click on `Create a new chart`
4. Observe that error is coming on right hand side explorer view

### Environment

- superset version: `master`
- python version: `3.6.5`
- node.js version: `8.9.4`
- npm version: `6.9.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

NA

**Comment by dfeldstarsky** [comment]
+1 on seeing this in production on `Superset 0.32.0rc2` 
Flask 1.0.2
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 

```node --version
v10.10.0
```

**Comment by doctording** [comment]
+1 on branch master 
![image](https://user-images.githubusercontent.com/11834821/57867266-66826e80-7833-11e9-8ae0-e84948c6fb21.png)

also there is a front problem: error messages on the right can not be seen fully (no scroll bar)

**Comment by michellethomas** [comment]
There's a workaround (in master) to get charts working until this bug is fixed, if you click on the + button under "Filters" on your filter box and then remove the control box that pops up that says "N/A" your chart should work even without adding additional filters. Once you do this save your filter chart and it should work.

It seems that this will work if you have `"filter_configs":[]` in form_data but existing slices don't have that param. I originally set this as a P1 but it could probably be a P2.

cc: @mistercrunch looks like an issue related to the filters change

**Comment by michellethomas** [comment]
fixed by #7593
