### ISSUE TITLE
Module 'signal' has no attribute 'SIGALRM' - Windows 

### ISSUE THREAD

**Issue by RobAndrade** [apache/incubator-superset#7492]
Hi Guys, 
I am aware that they have not implemented the SIGALRM module module in wndows and for this reason the superset has problems running SQL Lab.

I would like to ask the community for help if we can switch in python into the utils.py file for something equivalent (commands or routines) in windows.

I know that we already had a similar question on the forum, but no real solution answer.

### Expected results

what you expected to happen.

I hope I can use the tables of the databases added in the superset and also use SQL Lab

#### Screenshots

The SQL LAB Show the message: Module 'signal' has no attribute 'SIGALRM' and no work.

### Environment

- superset version:  0.32.0
- python version: 3.7
`

**Comment by RobAndrade** [comment]
Someone ? 


Best Regards

**Comment by mistercrunch** [comment]
We use it for this `timeout` "context manager":
https://github.com/apache/incubator-superset/blob/master/superset/utils/core.py#L520

Someone would have to re-write this in some other way like this
https://stackoverflow.com/questions/8420422/python-windows-equivalent-of-sigalrm

The real problem is we don't run test against windows and that no committers have committed to really get it to work or keeping it working. If someone from the community wants to actively work on this in a sustained kind of way, that could work.

**Comment by jornlp** [comment]
as a fix, I replaced the timeout class in utils/core.py with following class
(this requires the eventlet library though)
```
import eventlet
class timeout(eventlet.Timeout):
  def __init__(self, seconds=1, error_message="Timeout"):
    super(timeout, self).__init__(seconds, SupersetTimeoutException(error_message))
```
