### ISSUE TITLE
dashboard title not unique or show more on dashboards list page

### ISSUE THREAD

**Issue by doctording** [apache/incubator-superset#7548]
I have reproduced the issue with at least the latest released version of superset.
I have checked the issue tracker for the same issue and I haven't found one similar.

---

I add some dashboards,  for there are dashabords with same title, empty title etc.
I don't know which is which.  Is there an improvement for it. ( in my opinion, the title should be a required item and should not be empty)

![image](https://user-images.githubusercontent.com/11834821/57965890-16afbe80-797d-11e9-848e-fcf2f3e34244.png)

also when add a slice to a dashboard, which one should I choose. It's not friendly(more details should be displayed).

![image](https://user-images.githubusercontent.com/11834821/57968865-dd8a4500-79a2-11e9-887c-2cba058bc954.png)

**Comment by KilimAnnejaro** [comment]
Hi @doctording, thanks for this issue! So I can get an idea of how to help with this, I was wondering how you were using the dashboard add feature. In particular, if you add via code (rather than the GUI in the browser), the examples that are in this repo in the 'superset/data/' directory all directly add dashboards to the underlying database, rather than calling an internal method that has the potential to check uniqueness before adding a dashboard to the database. For your use case, would it be possible to modify one of these examples and create dashboards via code, rather than the GUI? (I'm a new volunteer and I think adding this feature is going to require a significant code refactor, which I'm very hesitant to do at this time.)

**Comment by doctording** [comment]
> Hi @doctording, thanks for this issue! So I can get an idea of how to help with this, I was wondering how you were using the dashboard add feature. In particular, if you add via code (rather than the GUI in the browser), the examples that are in this repo in the 'superset/data/' directory all directly add dashboards to the underlying database, rather than calling an internal method that has the potential to check uniqueness before adding a dashboard to the database. For your use case, would it be possible to modify one of these examples and create dashboards via code, rather than the GUI? (I'm a new volunteer and I think adding this feature is going to require a significant code refactor, which I'm very hesitant to do at this time.)

I want this like a file system
```
dashbord_directory1 
      dash1
      dash2
dashbord_directory2
     dash1(the same name of `dashbord_directory1`' dash1, but for different uses)
     dash3
```

one dashboard directory contains dashboards with unique name
different dashboard directories contain a different type of dashboard

**Comment by doctording** [comment]
In the production environment, there are many slices and dashboards, which serve different departments and different groups of a company. These dashboards and slices have different permission controls. For example, some dashboards are public and can be stored in public areas; some dashboards are privately owned by the department, stored in the department directory; some may be personally private, stored in a personal private directory.

This is just a practice in my company. Different companies do not necessarily have the same transformation. In short, this should be more user-friendly while meeting the data visualization needs of the company.
