### ISSUE TITLE
OAuth2 credentials rotation

### ISSUE THREAD

**Issue by tordingo** [apache/incubator-superset#7833]
Hi there!
I have a question regarding using superset with OAuth2.
I have my custom OAuth provider which rotates the credentials from time to time. 
Thing is that Superset doesn't support(or maybe it does?) credentials rotation.

There is another service which updates the credentials file. After that I can read these credentials with the help of something like [watchdog](https://github.com/gorakhargosh/watchdog). And then I'm not sure what to do, e.g. how to update current OAuth provider.

My question is: 
Can someone point on a possible workaround or other ways to implement this mechanism?
If I am asking in the wrong place, can you point to the right one or to the right person?

Any thoughts are appreciated!
Thanks!

**Comment by ericandrewmeadows** [comment]
@tordingo - interesting implementation.  What library are you using to accomplish the OAuth2 implementation?  Are you looking to have a background subprocess run that is pinging your service to ensure that the user re-authenticates after a certain period of time?

I am leveraging https://flask-oidc.readthedocs.io/en/latest/ for handling my authentication, so it may be a feature request for there.  If the above is the case, instead of having a watchdog, you can add in your timeout:  https://stackoverflow.com/questions/11783025/is-there-an-easy-way-to-make-sessions-timeout-in-flask#11785722
