### ISSUE TITLE
How to reload data in multiple charts on same dash faster?

### ISSUE THREAD

**Issue by miloradkrstevski** [apache/incubator-superset#7906]
Hi guys,

I was wondering if you could help me with the following issue:
1. I have one table with about 300k rows and 45 columns.
2. I have created many various charts, but even the filter boxes reload for 1-2-3 seconds.
3. On every change on any filter, the same 1-2-3 sec for reload of many charts (maybe not all).

How to fasten this reload? I have created multiple indexes in mysql db on many fields that I use, but this does not help a lot.

Can somehow data be cached before working hours in Superset or some ideas?

Thank you.

Regards.

**Comment by villebro** [comment]
Have you enabled redis or similar for caching? When caching is enabled only the first load will be slow (=fetch the data from the source), and subsequent dashboard views will get its data from the cache (usually sub-second load times). The cache can be warmed up automatically to make sure that even the first load is quick (not sure if it's comprehensively documented, though). However, there is a known bug affecting caching of Filterboxes, so that might be causing slowness. There is a PR to fix the bug that's currently pending review, see #7896.

**Comment by miloradkrstevski** [comment]
I haven't done this. Is it possible to explain me how to do it?

Thank you @villebro.

**Comment by mistercrunch** [comment]
http://superset.apache.org/installation.html#caching
