### ISSUE TITLE
Chart Explore - Datasource Tooltip Text

### ISSUE THREAD

**Issue by HendrikK** [apache/incubator-superset#7919]
When you hover over the data source name in the chart explore view, the tooltip states "Click to point to another datasource", whereas the click actually brings up the datasource semantic info.

### Expected results
Tooltip stating something like "Click to view/edit datasource semantic information"

### Actual results
Tooltip stating "Click to point to another datasource"

#### Screenshots
<img width="448" alt="Screen Shot 2019-07-24 at 9 29 33 AM" src="https://user-images.githubusercontent.com/4612319/61778098-05a88100-adf6-11e9-92f8-4c4875acda8e.png">

### Environment
- superset version: 0.28.1

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by MarcusSorealheis** [comment]
I believe this was fixed in subsequent versions, @hendrikK. If you upgrade to a newer version this is not an issue. I think this issue can be closed.

<img width="502" alt="Screen Shot 2019-08-11 at 9 10 14 AM" src="https://user-images.githubusercontent.com/2353608/62836452-e8f2b280-bc17-11e9-90f9-ab784d160800.png">
<img width="474" alt="Screen Shot 2019-08-11 at 9 10 25 AM" src="https://user-images.githubusercontent.com/2353608/62836453-e8f2b280-bc17-11e9-9ca2-bf75e9ee5edf.png">

**Comment by MarcusSorealheis** [comment]
The down arrow icon to the right gives more specific options for editing the data source.
