### ISSUE TITLE
cache warm up return 401

### ISSUE THREAD

**Issue by victortony** [apache/incubator-superset#7954]
I config the schedule task to warm up cache of slices as below. It is triggered at target time, but all the slices url returns 401. 
`CELERYBEAT_SCHEDULE = {
        'email_reports.schedule_hourly': {
            'task': 'email_reports.schedule_hourly',
            'schedule': crontab(minute=1, hour='*'),
        },
    }`
the log is : 
"GET /superset/explore_json/?form_data=%7B%27slice_id%27%3A+207%7D HTTP/1.1" 401 -
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mifercre** [comment]
I'm facing the same issue, even on current master the requests sent by the celery task end up on 302 redirect to the login page.
The problem is on this piece of code https://github.com/apache/incubator-superset/blob/master/superset/tasks/cache.py#L288 that sends the unauthenticated requests to the restricted explore endpoint. 

I've grabbed some code from the email reports celery task that is used to login and retrieve the session cookie and it fixes the issue, PR here: https://github.com/apache/incubator-superset/pull/9115
