### ISSUE TITLE
Not able to connect superset with BQ

### ISSUE THREAD

**Issue by bhuvanbhatia0807** [apache/incubator-superset#7969]
As a user I am not able to connect my superset with BigQuery. Currently I am running docker image on my local machine. I have installed the required pybigquery package and is passing the GCP project key but I am getting the following error: " sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:bigquery ". Attaching a screenshot for your reference. 
Can anyone guide me through the steps to do that. I can share my yml code too if anyone wants?

<img width="1237" alt="Screen Shot 2019-08-01 at 6 00 23 PM" src="https://user-images.githubusercontent.com/22019996/62336694-55d2b380-b486-11e9-8f08-a03a05d27aba.png">

**Comment by semantiDan** [comment]
Superset uses [SQLAlchemy ](https://www.sqlalchemy.org/) to manage database connections.

Currently, SQLAlchemy does not have an official dialect for BigQuery :(

If SQLAlchemy had a dialect and connector for BigQuery, it would have worked seamlessly for you as you expect it.

In order to make it work you need to either write a dialect and connector for BigQuery in SQLAlchemy by yourself or use an existing solution and integrate it.

Here is an existing solution (I haven't used it yet):
https://github.com/mxmzdlv/pybigquery

Then integrate the dialect into your SQLAlchemy module which according to your screenshot should be in the following folder:
/usr/local/lib/pythong3.6/site-packages/sqlalchemy/dialect/

You would also need to create a connector for BigQuery. You can see existing samples or follow the[ SQLAlchemy repository](https://github.com/sqlalchemy) or [documentation ](https://docs.sqlalchemy.org/en/13/contents.html) for more information.

Hope this helps!

**Comment by villebro** [comment]
Are you sure you've installed `pybigquery` correctly and restarted the server after that? I use BigQuery with Superset regularly and think it's very stable since at least 6 months.

**Comment by bhuvanbhatia0807** [comment]
Hi @villebro . Thanks for responding back. I am passing the module pybigquery=0.4.10 in the requirement.txt file in the docker that is being ran when I run the docker compose. So I am hoping that it is being initiated and is being installed along with the other modules. I checked and it is being installed in there. I am having the same error. Do I have to add any piece of code in any of the SQLAlchemy module?
If you can share any code snippet that needs to be alter, that would be great. 
I am attaching a screenshot for your reference.
<img width="1020" alt="Screen Shot 2019-08-05 at 1 59 02 PM" src="https://user-images.githubusercontent.com/22019996/62494946-7900aa00-b789-11e9-890f-96b6670cd2a1.png">

**Comment by bhuvanbhatia0807** [comment]
Thanks @semantiDan for providing the solution. I will try the method you have suggested and try writing a dialect and connector for Bigquery. Do you have any working solution link that you can provide and I can go over it that would be great. Thanks once again.
