### ISSUE TITLE
Dashboard filters do not persist on page refresh

### ISSUE THREAD

**Issue by smokemonster99** [apache/incubator-superset#8102]
Dashboard filters do not persist on page refresh.

### Expected results
The page reloads with the same values for filters

### Actual results
The filters reset to defaults. 

#### How to reproduce the bug

1. Load a dashboard which contains filters
2. Use dropdown to select one the the filters and hit apply
3. Refresh the browser 
4. Previously applied filter does not get applied (filters not retained)

### Environment

(please complete the following information):

- superset version: 33.0 (and 26.3)
- python version: 3.6.8
- node.js version: v10.16.0
- npm version: 6.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.
Issue #5628 is same but the PR does not seem to address this issue., only dashboard refresh interval issue.

### Additional context
I am also open to a workaround or change in config that would enable this desired behavior

**Comment by kaspergaj** [comment]
After applying filters: 
Press the arrow next to "Edit dashboard". 
"Save as"

That should do it.

**Comment by kaspergaj** [comment]
How about the _share dashboard_ button under _save as_? That should give you a link. When I follow that link it keeps the selected filters.

**Comment by smokemonster99** [comment]
Yes but this does not work on v0.26.3.

**Comment by avinasht1** [comment]
Desperately need this feature. I have around 15 filters in my dashboard and would like to share the dashboard with others without having to save a copy of dashboard. 
The dashboard also looses filters on refresh which I have to due to web server timeout errors. 

It would be great if filter values are added to Dashboard URL like it does in explore view.

**Comment by mistercrunch** [comment]
@graceguo-supercat

**Comment by mistercrunch** [comment]
oh @avinasht1 , just use the "share dashboard" link, it saves the filter context
<img width="260" alt="Screen Shot 2019-09-25 at 9 40 38 PM" src="https://user-images.githubusercontent.com/487433/65658578-2c915800-dfdd-11e9-8547-ff419cbc1666.png">
<img width="310" alt="Screen Shot 2019-09-25 at 9 40 16 PM" src="https://user-images.githubusercontent.com/487433/65658579-2c915800-dfdd-11e9-9095-ac2cfeb69cd3.png">

**Comment by graceguo-supercat** [comment]
I just saw this thread. Max is right: 
1. apply filter on your dashboard,
2. open dropdown menu and choose `Share dashboard`, it will generate a shorten url. this url encode current selected filter values.
This way you don't have to save another copy of dashboard, but your users need to keep a copy of shorten url, otherwise they will lost the filter values in the url parameters.

Or you can 
1. apply filter on your dashboard,
2. open dropdown menu and choose `Save as` => save as another copy. 
This way the selected filter values are stored in dashboard's meta data. Dashboard users can open dashboard by id, and it will load preselected values.

**Comment by Matthew-Byrne** [comment]
Hi, I see the work around options above but is there a plan to add a feature so the filters are automatically added to the url when selected? This would prevent our users from losing the filters they've applied when refreshing the page.
