### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by oakley04** [apache/incubator-superset#8400]
pip install --index-url https://pypi.tuna.tsinghua.edu.cn/simple/ superset

### Actual results
copying superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f\4e8df4f5ee7921b2270d4e4b41484d51b0f9179c662a55d62128f18abf1686780a3620666b8d0f53752f414c3c1bdf8cafd5de04e357c01b4ec561ab7581 -> build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f
    error: could not create 'build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f\4e8df4f5ee7921b2270d4e4b41484d51b0f9179c662a55d62128f18abf1686780a3620666b8d0f53752f414c3c1bdf8cafd5de04e357c01b4ec561ab7581': No such file or directory

### Environment

- python version: Python 3.6.8

[log.txt](https://github.com/apache/incubator-superset/files/3733516/log.txt)

**Comment by oakley04** [comment]
> change pip source to douban

tried douban, same error..

**Comment by dpuser6** [comment]
Restore the default source.
change the tsinghua source after the package is installed

**Comment by wtfzambo** [comment]
Nah, this issue is most likely due to long paths being disabled in windows by default (yay microsoft...).
I had the same problem one week ago, fixed it like this:
- type `regedit` in windows search
- navigate to: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSytem
- look for a key called "LongPathsEnabled"
- double click, change value from 0 to 1
- restart computer

**Comment by viking714** [comment]
I meet this problem too, hope it can help me.
