### ISSUE TITLE
Long run query support in Chart Query

### ISSUE THREAD

**Issue by leon90dm** [apache/incubator-superset#8526]
**Is your feature request related to a problem? Please describe.**
I've set up Celery task with the following config:

```
class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = (
        'superset.sql_lab',
        'superset.tasks',
    )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERYD_LOG_LEVEL = 'INFO'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'sql_lab.get_sql_results': {
            'rate_limit': '100/s',
        }
    }
    CELERYBEAT_SCHEDULE = {
    }

CELERY_CONFIG = CeleryConfig
```
Sql lab seems work OK when fire long run query, PENDING status changes to RUNNING.  But In Chart Tab, after fired query button,  breaking with timeout. 
Or Chart Query doesn't support async long run query?  Why?

**Additional context**
- x86_64 GNU/Linux
- Python 3.6.9
- Flask 1.1.1
- Werkzeug 0.16.0

**Comment by rubypollev** [comment]
Charts & dashboards do not support async query execution because the assumption is that they are interactive (finishing quickly, under 60 seconds). 

That assumption should not be made of the user. It can be opinionated, but I should be able to override that opinion and use an async backend for charting (maybe a feature flag?). Some queries are not interactive, but still need to be visualized.
