### ISSUE TITLE
Filter Boxes with a large number of items are slow

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8666]
UI performance for filter boxes with a large number of possible items are very slow when typing and searching

### Expected results

This should be performant up to at least 10k items as it should be virtualized

### Actual results

It's not performant

#### How to reproduce the bug

1. Create a filter box with a high cardinality filter
2. See typing and searching for values in the filterbox is slow

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@etr2460 I tried to repro this issue by generating a random set of ~17k email addresses and didn't notice a huge performance issue. Do you have any more context on this? Was this filter on a dashboard with a lot of charts? 

Looks like the filter box searching and filtering is all handled client side, so performance is heavily dependent on the client. Do you know what type of environment this bug was encountered in?
