### ISSUE TITLE
How does Gunicorn workers improve Superset's performance?

### ISSUE THREAD

**Issue by max-123-rich** [apache/incubator-superset#8751]
I'm using 10 gunicorn workers to run superset. 

1. When multiple users are accessing superset at the same time, will these workers get split among the users?
2. While loading a dashboard, only 6 queries are running concurrently, is there a way to increase that number?

**Comment by willbarrett** [comment]
🏷 #question

**Comment by willbarrett** [comment]
@max-123-rich it depends on how you have Gunicorn configured. For more information on the concurrency options, check out Gunicorn's design documentation: http://docs.gunicorn.org/en/latest/design.html#design

There is a limit imposed by browsers on the number of concurrent connections you can have open to a single domain. That may be what you're running into. You can get around that via domain balancing requests (splitting requests between multiple domains).

**Comment by LeoDiep** [comment]
> @max-123-rich it depends on how you have Gunicorn configured. For more information on the concurrency options, check out Gunicorn's design documentation: http://docs.gunicorn.org/en/latest/design.html#design
> 
> There is a limit imposed by browsers on the number of concurrent connections you can have open to a single domain. That may be what you're running into. You can get around that via domain balancing requests (splitting requests between multiple domains).

Hi @willbarrett 
I enable function sharding domain and add 5 sub domains on superset_config.py
This dasboard contain 14 tables which query into postgresql superset db and now requests are now split into different domains  but the performain is not getting better (Left use sharding domains and Right use single domain). Now instead of having stalled time, I have more wait time for server to response.
Is it because docker default config doesn't have enough worker or threads to handle requests of sharding domain or other reasons. And how would I config to get more workers, threads in superset docker.
Please help me with this. Thank you a lot
![image](https://github.com/apache/superset/assets/99783557/5c67d5a5-979b-4382-9f95-2d2841b6de80)
