### ISSUE TITLE
Document how to create a completely fresh reinstall of Superset

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8844]
[Here](https://github.com/apache/incubator-superset/issues/8795#issuecomment-564113924) we read:

> create a clean/new virtualenv and reinstall superset and dependencies

without a link to anywhere in the docs stating how to reinstall superset and erase any previous install. for instance, the database in `$HOME/.superset/superset.db` needs to be removed for a new installation to truly work.

reinstalling superset without doing so will create database clashes when you attempt to create the admin user.

**Comment by dpgaspar** [comment]
Hi @metaperl,

The default database location is referenced here: https://superset.apache.org/installation.html#configuration

Don't know if updating the docs stating that user's can/should remove sqllite db on a reinstall is the right way to go, could further increase confusion around the process. 

Yet, I'll update flask-appbuilder so that `flask fab create-admin` won't raise an exception if a user already exists
