### ISSUE TITLE
Tables/charts are not listed for custom-role user.

### ISSUE THREAD

**Issue by nellyblu** [apache/incubator-superset#8927]
User with custom role + gamma can create a table, but this table is not listed. Same for charts.
For Dev version 0.999 it works, i.e. the tables are listed. With 0.35.1 version, with same configuration, the tables and charts are not listed.

### Expected results
Permitted and created tables and charts are listed for the custom user.

### Actual results

Permitted and created tables and charts are not listed for the custom user (for version 0.35.1). For dev version 0.999 it is listed.

#### How to reproduce the bug

1. Create a custom role:
nelly1r | [can delete on TableModelView, can edit on TableModelView, can show on TableModelView, can add on TableModelView, can list on TableModelView, refresh on TableModelView, schema access on [small-aurora].[nelly1], database access on [small-aurora].(id:2)]
2. Create a custom user nelly1 with Gamma and nelly1r roles - ok
2.1 Login with nelly1 user - ok
3. Create a table source tbl_src, referring to [small-aurora].[nelly1].tbl1 - ok
4. Create a chart, referring to tbl_src, created above - ok
5. A new dashboard is created and can be shown - ok
6. Go to Sources/Tables - empty list - problem in 0.35.1
7. Charts - also empty - problem in 0.35.1
 
### Environment

(please complete the following information):

- superset version: 0.35.1
- python version:  3.6.9
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by helo-ch** [comment]
I'm encountering the same issue : 

User has Gamma + sql_lab + 2 custom roles : 
- DB_ACCESS : `database access on [Timescaledb XXX].(id:3)`
- tables_modify : `[can edit on TableModelView, can add on TableModelView, can list on TableModelView, can show on TableModelView, can tables on Superset, refresh on TableModelView, can save on Datasource, can get on Datasource, can datasources on Superset, menu access on Tables, can list on TableColumnInlineView, can show on TableColumnInlineView, can fetch datasource metadata on Superset]` 

User can : 
- create charts, add them to dashboard
- see dashboard
- see charts in dashboards and edit them from there

But they cannot see their own Charts listed in Charts Menu.

Is this the expected behaviour? Is there some other permission we need to add in order for users to see their own charts?

**Comment by jkleinkauff** [comment]
Hey,

has anyone found a fix for this one? @helo-ch seems to get it https://github.com/apache/superset/issues/12041, but I think the problem is when DASHBOARD_RBAC is on:

when adding `schema access on [database].[schema]` and DASHBOARD_RBAC is active, it seems that I can see all dashboards listed, even if my role was not attached to it. So when I try to open I see "Unexpected error".
