### ISSUE TITLE
Docker build image from Windows

### ISSUE THREAD

**Issue by stevensotelo** [apache/incubator-superset#8983]
It is not possible to build a image from Dockerfile, because it has a error when I'm trying to build the image.

### Actual results

11% building 9/18 modules 9 active ...set/assets/src/showSavedQuery/index.jsxBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`                                                                   92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`                               92% chunk asset optimization TerserPluginThe command '/bin/sh -c cd superset/assets && npm ci && npm run build && rm -rf node_modules' returned a non-zero code: 137

#### How to reproduce the bug

1. docker build -t stevensotelo/aeps_superset:latest .

### Environment

- superset version: `master`
- python version: `python version 3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm guessing this has to do with the linux-only symlink that's used in the build. This SIP may address that issue: #8805

**Comment by willbarrett** [comment]
Hi @stevensotelo - the exact error you are running into is due to insufficent RAM being allocated to Docker to complete the build. I've been recommending a minimum of 6GB be assigned to the Docker system. However, @rusackas is correct. Windows is not currently a supported platform, even using Docker. I would recommend running this inside of a Linux VM if you are tied to Windows, or installing it on a hosted Linux machine. We're still looking for a contributor who would want to take on creating the build pipelines for Windows and handling incompatibility issues. If you're interested let us know.

**Comment by stevensotelo** [comment]
@willbarrett, sure, how I can contribute?

**Comment by willbarrett** [comment]
@stevensotelo glad you're interested! Currently, most Apache projects use Travis for CI. Travis has limited support for Windows builds. A good first step would be forking Superset and working towards getting a Docker build running under Travis's Windows CI system. We'd be open to suggestions on other ways to accomplish this, that's just what comes to mind.

**Comment by stevensotelo** [comment]
Actually I could create a image from Windows. You can see in https://github.com/CIAT-DAPA/aeps_platform_docker/blob/master/aeps_visualization_superset/Dockerfile

**Comment by willbarrett** [comment]
Closing, as @stevensotelo was able to create an image. Woot!
