### ISSUE TITLE
MFA Options?

### ISSUE THREAD

**Issue by alecialee** [apache/incubator-superset#8989]
Hello,

Just wondering if there are any options for using MFA for Superset. I searched through the documentation, but was unable to find anything for "MFA" or "multi-factor authentication". If this is an option what MFA platforms are an option? And can you point me to the section in the docs that deals with setting this up? If this isn't a current feature, is it on the roadmap?

Thank you in advance!
-Alecia

**Comment by nytai** [comment]
Hi @alecialee, superset does not currently support any native MFA functionality (that I know of). It does provide a way to override some of the security manager's functionality so that you can delegate to your own authentication system. Here's some documentation about the security manager: https://flask-appbuilder.readthedocs.io/en/latest/security.html

Something that comes to mind, ss you could use OAuth and then rely on your oauth provider to handle MFA. Something like https://auth0.com/ and google should have options for forcing users to use MFA. 

As for the roadmap, I do not know of any current plans to add MFA functionality to superset.

**Comment by alecialee** [comment]
Thank you @nytai . I'll look into it. 

-Alecia
