### ISSUE TITLE
[Big Number with Trendline ] sql bug

### ISSUE THREAD

**Issue by zhxjdwh** [apache/incubator-superset#9071]
the [Big Number with Trendline ]  generated sql ,
   the where sql should be ` timecol  >= beginTime and timecol < endTime ` ,
but in superset-0.34.0,
   the where sql is :  `  timecol  >= beginTime and timecol <= endTime ` ,

### Expected results

` where timecol  >= beginTime and timecol < endTime ` 

#### Screenshots

![TIM图片20200203005037](https://user-images.githubusercontent.com/9401765/73619618-284f0880-4669-11ea-8f86-fff60069e695.png)

### Environment

(please complete the following information):

- superset version: `superset version`
 superset-0.34.0
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

**Comment by john-bodley** [comment]
@zhxjdwh this issue is described in [SIP-15](https://github.com/apache/incubator-superset/issues/6360)  and a solution was introduced in 0.36. To enable it you will have to set the [SIP_15_ENABLED](https://github.com/apache/incubator-superset/blob/0.36/superset/config.py#L741) flag to `True`. Note in `master` the default value is now `True`.

**Comment by zhxjdwh** [comment]
@john-bodley thanks
