### ISSUE TITLE
default Docker-compose creates an "unhealthy" superset-worker container

### ISSUE THREAD

**Issue by PRamia** [apache/incubator-superset#9128]
Hi,

when i just run the docker-compose for superset, just with the default configuration, the superset-worker container has an unhealthy status.

This is relevant for me because i am trying to use the email reporting option, and the communication between superset with worker is failing. 

Related with this topic, docker-compose doesn't includes the email components and i found any good documentation about how to implement it using docker. It would be nice if somebody could share a working setup to run docker superset with a standard email feature implemented. 

I was looking into other tickets, where is suggested to install geckodriver via Dockerfile:

`wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux32.tar.gz`
`tar -xvzf geckodriver-v0.24.0-linux32.tar.gz`
`chmod +x geckodriver`
`mv geckodriver /usr/local/bin/`
`rm -f geckodriver-v0.24.0-linux32.tar.gz`

And also firefox-esr and Xvfb are needed, so i am installing those packages via Dockerfile. Then there is a debug work to do in order to get it working.

This try-fail workaround is a pain, that's why i am asking for your help!

Thanks in advance! :)

**Comment by riyazbhanvadia** [comment]
Hi Try following command,

It works for me

git clone https://github.com/apache/incubator-superset/
cd incubator-superset/docker
# prefix with SUPERSET_LOAD_EXAMPLES=yes to load examples:
docker-compose run --rm superset ./docker-init.sh
# Run below command in incubator-superset/docker
docker-compose up

**Comment by buzzware** [comment]
@riyazbhanvadia makes an important point. that the commands should be run from inside the docker folder, and the docker-init line seems to be necessary.

On a fresh instance of Ubuntu 20.04, the following works :
The trick is you need to be in the docker folder, and you run
"sudo docker-compose run --rm superset ./docker-init.sh"
before "docker-compose up".
I got that from this : https://medium.com/@dheerajsharmainampudi/installing-superset-docker-on-an-ubuntu-16-04-ec2-instance-76bc160cf38f
 
Note: this uses 8192MB memory to ensure memory is not an issue, but the install checks for at least 3GB, so 4096MB should be plenty.
 
grep -cw vmx /proc/cpuinfo # should return something, otherwise enable virtualization nesting
sudo apt update
sudo apt install git virtualbox docker docker-compose
git clone https://github.com/apache/incubator-superset.git
cd incubator-superset/docker
base=https://github.com/docker/machine/releases/download/v0.16.0 &&   curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&   sudo mv /tmp/docker-machine /usr/local/bin/docker-machine &&   chmod +x /usr/local/bin/docker-machine
docker-machine create --driver virtualbox --virtualbox-memory="8192" --virtualbox-cpu-count="4" default
docker-machine env default
eval $(docker-machine env default)
sudo docker-compose run --rm superset ./docker-init.sh
sudo docker-compose up
