### ISSUE TITLE
Public Role

### ISSUE THREAD

**Issue by iamklaus** [apache/incubator-superset#9674]
I followed the documentation to grant access via public role to unauthorized users. I have also set PUBLIC_ROLE_LIKE_GAMMA = True in the config file.

Partly the access works, but superset gives the following message to the visitor:

"An error occurred while fetching available CSS templates"

Bug or missing configuration?

**Comment by MarcusSorealheis** [comment]
Need a lot more info to reproduce

**Comment by aspedrosa** [comment]
@MarcusSorealheis 
I think what @iamklaus is trying to do is to access dashboards without logging in.
I have a similar/related issue. I'm not setting PUBLIC_ROLE_LIKE_GAMMA to True but I'm giving the necessary permissions to the public role so he can access a dashboard, however without success.

I think the problem is on the method get_public_role of the SupersetSecurityManager [here](https://github.com/apache/incubator-superset/blob/master/superset/security/manager.py#L368) :point_down: 

```
if not conf.get("PUBLIC_ROLE_LIKE_GAMMA", False):
    return None

from superset import db

return db.session.query(self.role_model).filter_by(name="Public").first()
```

Shouldn't it be like this :point_down: ?
```
from superset import db

if conf.get("PUBLIC_ROLE_LIKE_GAMMA", False):
    return db.session.query(self.role_model).filter_by(name="Gamma").first()

return db.session.query(self.role_model).filter_by(name="Public").first()
```

**Comment by aspedrosa** [comment]
@iamklaus You have to also add the permission "can list on CssTemplateAsyncModelView"

**Comment by andreaphsz** [comment]
I am struggling with the same issue. Is there an update on this?

**Comment by extssam** [comment]
> I am struggling with the same issue. Is there an update on this?

When I created a dashboard and marked the table under Public along with some more permissions, I got the same error. "An error occurred while fetching available CSS templates"

After adding required permissions, it worked. Please see screenshot below for reference.
![image](https://user-images.githubusercontent.com/52645723/125285912-d9100b80-e323-11eb-8fa8-229538235273.png)
